//# sourceMappingURL=module-profile.js.map
(function(g,r,n,y,t,$b,ac,bc){__mtm_tags._profiler=function(ea,ja,Ya,Za,p,T){function X(a){z.href=a;return z.href}function C(a){return a.replace(/#.*$/,"")}function ka(a){return a.replace(/^(https?|resource):\/\//i,"")}function U(a){return/^(?:javascript|data|about|blob|resource):/i.test(a)}function N(a){a=ka(a);return $a&&$a.test(a)||Ca&&a.substring(0,Ca.length)==Ca||g.__mtm&&__mtm[1]&&__mtm[1].length&&a.substring(0,__mtm[1].length)==__mtm[1]}function Y(a,b){var c=a.offsetWidth,d=a.offsetHeight;
if(c&&d)return b.a=[Math.round(c),Math.round(d)],1}function cc(a){for(var b=[],c;c=dc.exec(a);)c=X(c[1]||c[2]||c[3]),U(c)||N(c)||b.push(c);return b}g.__mtm_spy++;var L=g.__mtm_start,I=__mtm_tags._api,J=g.performance,D;D=J&&J.now?function(a){var b=J.now();return Math.round(a&&36E5>=Math.abs(b-a)?a:b)}:function(a){var b=(new Date).getTime();if(a){if(36E5>=Math.abs(b-a-L))return Math.round(a);a>1E3*(b-36E5)&&(a=Math.round(a/1E3));a=36E5<Math.abs(b-a)?0:Math.round(a)}return(a||b)-L};I.getTimeOffset=D;
var A={},fa={},R={},la=function(a,b){var c=fa[a];c?1==c.length&&c[0]!=b&&c.push(1):fa[a]=[b]},aa=[],Da=function(a,b,c){if(!A[b]){c&&(a.pr=c);for(var d=a.s,e=a.ty,h=0,k=aa.length;h!=k;h++){var f=aa[h];if(f.pr==c&&f.s==d&&f.ty==e){for(var g in f)a[g]=f[g];aa.splice(h,1);break}}A[b]=a;d&&"SCRIPT"==e&&(la(d,b),c=C(d),c!=d&&la(c,b));Ya&&Ya(a)}};I.addVirtProfilingRecord=function(a,b,c){b&&(a.pr=b);c?(aa.push(a),p.setTimeout(function(){p.setTimeout(function(){var c=aa.indexOf(a);0<=c&&aa.splice(c,1)},0)},
0)):(a.virt=1,a.t={e:D()},A[B()]=a)};var Ea=[],G=I.getProfilingNodeInfo=function(a){return R[a]||(R[a]={})},ga={},ab=function(a,b){ga[b]=a;var c=R[b];if(c){var d=R[a];if(d){if(c.f||d.f)c.f=O(c.f||0,d.f||0);d.e&&(c.e=c.e?c.e.concat(d.e):d.e);if(c.ts||d.ts)c.ts=c.ts&&d.ts?Math.min(c.ts,d.ts):c.ts||d.ts;!c.tr&&d.tr&&(c.tr=d.tr);if(c.te||d.te)c.te=c.te&&d.te?Math.max(c.te,d.te):c.te||d.te;if(d.y)if(c.y)for(var e=0,h=d.y.length;e!=h;e++){var k=d.y[e];0>c.y.indexOf(k)&&c.y.push(k)}else c.y=d.y}R[a]=c}else R[b]=
G(a)},ec={text:-1,number:-1,password:2,email:1,tel:8},fc={firstname:5,lastname:5,namefirst:5,namelast:5,name:5,email:1,zip:3,postalcode:3,postal:3,city:3,country:3,address:3,state:3,login:4,username:4,nickname:4,phone:8,tel:8,age:6,birthday:7,birthdate:7,dateofbirth:7,dob:7},bb={"postal code":3,zip:3,address:3,phone:8,birthday:7,"birth day":7,"date of birth":7},z=r.createElement("a"),O=function(a,b){if(1073741824>a&&1073741824>b)return a|b;var c=a.toString(16),d=c.length-7,e=b.toString(16),h=e.length-
7;return(parseInt(c.substring(d),16)|parseInt(e.substring(h),16))+268435456*((parseInt(c.substring(0,d),16)||0)|(parseInt(e.substring(0,h),16)||0))},ba={SCRIPT:["src"],IMG:["src"],IFRAME:["src"],OBJECT:["data"],EMBED:["src"],VIDEO:["src","poster"],AUDIO:["src"],SOURCE:["src"],AREA:["href"],TRACK:["src"],LINK:["href"],INPUT:["src"]},gc={IMG:1,VIDEO:1,AUDIO:1},cb={IMG:[g.Image,g.HTMLImageElement],VIDEO:[g.HTMLVideoElement],AUDIO:[g.HTMLAudioElement],LINK:[g.HTMLLinkElement],INPUT:[g.HTMLInputElement]},
hc={LINK:{rel:"stylesheet"},INPUT:{type:"image"}},Fa=function(a,b){var c=hc[a];if(c)for(var d in c){var e=b.getAttribute(d);if(!e||e.toLowerCase()!=c[d])return}return 1},db={startTag:1,atomicTag:1},ma=r.currentScript,Ga=ma&&ma.src&&C(ma.src),Ca=Ga&&ka(Ga).replace(/\/[^\/]*$/,"/"),Ha=0<n.userAgent.indexOf("Gecko/"),ic={SCRIPT:1,NOSCRIPT:1,STYLE:1,META:1,HEAD:1,LINK:1,SOURCE:1},eb={IMG:1,IFRAME:1,OBJECT:1,EMBED:1,VIDEO:1,AREA:1,INPUT:1},jc={SCRIPT:["text/javascript","application/javascript","text/ecmascript",
"application/ecmascript"],LINK:["text/css"],OBJECT:["application/x-shockwave-flash"],EMBED:["application/x-shockwave-flash"]},$a=/^(?:stats\.(?:[a-zA-Z]+\.)?mezzobit\.com|cdn01\.mzbcdn\.net|[a-zA-Z]{3}\.mezzobit\.com)\//i,dc=/\burl\(\s*(?:([^"'][^\)]*)|"([^"]+)|'([^']+))/g,fb=function(a,b,c,d){var e={SUBDOCUMENT:"IFRAME",OTHER:"HTML",XMLHTTPREQUEST:"AJAX",IMAGE:"IMG","":"ICON"},h=function(a,c){for(var b=0,d=a.length;b!=d;b++){var e=a[b],h=e.src;if(h&&(h==c||C(h)==c))return e}},k=function(e,h,f,F,
s,r,l,q){if(1==h.nodeType){var u=h.childNodes;if(u)for(var w=0,V=u.length;w!=V;w++)k(e,u[w],f,F,s,r,l);var H=h.nodeName.toUpperCase();if(!(r&&"IFRAME"==H&&0<=r.indexOf(h))){s=a[H];var x=h.attributes;if(s&&b(H,h)){var p;s.forEach(function(a){if((a=x[a]&&x[a].value)&&!c(a)&&(a=X(a),!(d(a)||F&&F[a]))){var b={ty:H,s:a,o:1};Y(h,b);if((l||q)&&"SCRIPT"==H){var k=x.mtmid;k&&(k=k.value,l&&l(k,b),q&&(b.key=k))}f&&((k=f.getEntriesByName(a))&&k.length||(k=f.getEntriesByName(C(a))),k&&1==k.length&&(b.t={s:Math.round(k[0].startTime),
e:Math.round(k[0].responseEnd)},b.t.r=b.t.e));e.push(b);p=1}});p||"IFRAME"!=H||g(e,h)}}}},f=function(a,b,f,F,s,l,q,p,u){var w,V,H;b&&(V=b.ownerDocument,H=V.scripts);var x=f&&f.getEntriesByType;x&&(w=f.getEntriesByType("resource"),H&&Ha&&!w.length&&!H[0]&&(w=0));if(w){var v=V&&V.images,n={};F=r.getElementsByTagName("STYLE");w=0;for(x=F.length;w!=x;w++){var t=F[w].getAttribute("mtmparent");cc(F[w].textContent).forEach(function(a){var b=C(a);"undefined"==typeof n[b]&&(n[a]=n[b]=t)})}var A={IMG:v||0};
f.getEntriesByType("resource").forEach(function(b){var f=b.name;if(!(c(f)||d(f)||s&&s[f])){var k=b.initiatorType.toUpperCase(),g;v&&Ha&&"OTHER"==k&&(g=h(v,f))&&(k="IMG");b={ty:e[k]||k,s:f,o:1,t:{s:Math.round(b.startTime),e:Math.round(b.responseEnd)}};if(V&&eb[k]){if(!g){var Z=A[k];0!==Z&&(Z||(A[k]=Z=V.getElementsByTagName(k)),g=h(Z,f))}g&&Y(g,b)}b.t.r=b.t.e;var m;if(H&&(p||u)&&"SCRIPT"==k){if(f=h(H,f))if(b.s=f.src,f=f.getAttribute("mtmid"))p&&p(f,b),u&&(b.key=f)}else if(q&&"CSS"==k&&"undefined"!=
typeof(m=n[f]))if(m){if(f=q(m)){f.c||(f.c=[]);delete b.o;f.c.push(b);return}}else delete b.o;a.push(b)}});if(b)for(b=b.querySelectorAll("iframe"),f=0,F=b.length;f!=F;f++)if(w=b[f],!(l&&0<=l.indexOf(w))){if(x=w.attributes.src)x=x.value;x&&!c(x)||g(a,w)}}else b&&k(a,b,x?f:0,F,s,l,p,u)},g=function(a,b,c){try{var d=b.contentDocument;d&&f(a,d.documentElement,b.contentWindow.performance,0,0,0,0,0,c)}catch(e){}};return[g,f]}(ba,Fa,U,N),gb=fb[0],kc=fb[1],na=134219776,hb,ib=function(a){for(var b=a.length-
1;0<=b;b--){var c=a[b];c.c&&!c.c.length&&delete c.c;ja(c)?c.c&&(ib(c.c),c.c.length||delete c.c):c.c?(a.splice.apply(a,[b,1].concat(c.c)),b+=c.c.length):a.splice(b,1)}},jb=function(a){var b=a.match(/^(?:Uncaught\s+)?([^:]*):\s*(.*)$/i);return b?[b[1].trim(),b[2]]:[0,a]},oa=function(a){return A[a]||A[ga[a]]},kb=function(a){var b=ea[a]||ea[ga[a]];if(b)return{tid:b.id};b=r.currentScript;if(!b||b.getAttribute("mtmid")!=a||b.getAttribute("mtmparent")==a){for(var c=r.querySelectorAll("script[mtmid="+a+"]"),
d,e=0,h=c.length;e!=h;e++)if(b=c[e],b.getAttribute("mtmparent")!=a){d=1;break}if(!d)return}if(b)return{pr:b.getAttribute("mtmparent"),s:b.src}};I.getProfilerRealDataNode=function(a){for(;a=oa(a)||kb(a);){if(a.s)return a;if(!(a=a.pr))break}};var lc=function(a){for(var b;a&&(b=a.pr);)if(!(a=oa(b)))return;return b};I.getProfilerRootNode=function(a){for(var b;b=oa(a)||kb(a);)if(!(a=b.pr))return b};var $=[],lb=function(a){var b=a.indexOf(";");0<=b&&(a=a.substring(0,b));return a.toLowerCase()},mb=function(a,
b){var c=$.indexOf(b);0>c&&($.push(b),c=$.length-1);a.n=c},nb=function(a,b){if(a)for(var c=0,d=a.length;c!=d;c++){var e=a[c],h=e.t;if(h)for(var k in h)h[k]+=b;e.c&&nb(e.c,b)}},ob=function(a){var b={};a.forEach(function(a){var d=(a.i||"")+"-"+(a.b||"")+"-"+a.m;b[d]?b[d].c++:(a.c=1,b[d]=a)});return b},pb=function(a){var b=[],c;for(c in a){var d=a[c];1==d.c&&delete d.c;b.push(d)}b.sort(function(a,b){return a.t-b.t});return b},pa={},Ia={IMG:1,CSS:1},qb=function(a){if(a){var b={},c;for(c in Ia)b[c]={};
var d=[];a.forEach(function(a){var c=b[a.ty];if(c&&a.s){z.href=a.s;var e=(a.j?a.d||"u":"")+"-"+z.protocol+"-"+z.host;c[e]?c[e].push(a):c[e]=[a]}else d.push(a),a.c&&(a.c=qb(a.c))});var e,h,k=function(a){h[a]=1};for(c in Ia){var f=b[c],g;for(g in f){var K=f[g],m=K.length;if(20<m){e=K[20];var M=e.t;h={};e.k&&e.k.forEach(k);var F=0,s=0,l=0,r=function(a){if(a=a.a)F+=a[0],s+=a[1],l++};r(e);for(var p=21;p!=m;p++){var u=K[p];r(u);var w=u.t;w.s&&(!M.s||M.s>w.s)&&(M.s=w.s);w.r&&(M.r||0)<w.r&&(M.r=w.r);u.f&&
(e.f=O(e.f||0,u.f));u.o||delete e.o;u.j&&(e.j=(e.j||0)+u.j);u.b&&(e.b=(e.b||0)+u.b);u.k&&u.k.forEach(k)}e.g=m-20;F&&s&&(e.a=[F/l|0,s/l|0]);m=t.keys(h);m.length&&(e.k="undefined"!==typeof enableHeavyStatistics&&enableHeavyStatistics?m:5<m.length?m.slice(0,5):m);M.e=M.r;K.splice(21);e=1}}}if(e)for(c in a=d,Ia)for(g in f=b[c],f)a=a.concat(f[g]);return a}},rb=function(a,b){a.forEach(function(a){"number"==typeof a.n&&b[a.n]&&(a.n=b[a.n]);a.c&&rb(a.c,b)})},mc=function(a,b,c){if(c){var d={},e;b.forEach(function(a,
b){var f=c.indexOf(a);0>f&&(c.push(a),f=c.length-1);b!=f&&(d[b]=f,e=1)});e&&rb(a,d);return c}return b},nc=function(a,b){var c=function(a,b){if(b.c)for(var d in b.c)c(a,b.c[d]);a.push(b)},d=[],e;for(e in a)c(d,a[e]);for(var h in b)for(var k in b[h])e=b[h][k],0>d.indexOf(e)&&(e.o=1,a.push(e))},v=function(a,b){if(b||(b=E())){var c=G(b);c.f=O(c.f||0,a||0);return c}},q=function(a){na=O(na||0,a)},Ja=function(a,b){if(!ic[b]){var c=a.offsetWidth,d=a.offsetHeight,e=a.offsetLeft,h=a.offsetTop;return c&&d?0<
e+c&&0<h+d:eb[b]&&-1E3<e&&-1E3<h}if("STYLE"==b||"LINK"==b&&(c=a.getAttribute("rel"))&&"stylesheet"==c.toLowerCase())return 1},oc=0,B=function(){return"m"+oc++},pc=I.htmlMutatorHooks=[],qa=function(a,b,c){var d;pc.forEach(function(e){e(a,b,c)&&(d=1)});return d};__mtm_tags._writerModifiers||(__mtm_tags._writerModifiers=[]);__mtm_tags._writerModifiers.push(function(a,b,c){if(g.__mtm_spy){var d=a.attrs,e;db[a.type]&&(e=a.tagName.toUpperCase());var h;if(b)c=c.mtmsid,qa(a,c,1),e&&(b=a.text,"SCRIPT"!=e&&
ba[e]?(d.mtmid=h=B(),a.text=b.replace(/(\/?>)/," mtmparent="+c+" mtmid="+h+" $1")):a.text=b.replace(/(\/?>)/," mtmparent="+c+" $1"),d.mtmparent=c);else if(e){var k=E();qa(a,k,1);b=a.text;var f=("SCRIPT"!=e||!c)&&(ba[e]||"STYLE"==e);f&&(G(d.mtmid=h=B()).ts=D(),a.text=b.replace(/(\/?>)/," mtmid="+h+" $1"));k&&(f&&(a.text=b.replace(/(\/?>)/," mtmparent="+k+" $1"),d.mtmparent=k),!c&&("SCRIPT"==e&&null!=d.async&&d.src||"LINK"==e&&d.rel&&"stylesheet"==d.rel.toLowerCase()||"STYLE"==e&&b&&b.match(/\b@import[\s'"]/))&&
v(1,k))}else qa(a)}});var qc=g.MutationObserver||g.WebKitMutationObserver,sb=function(a,b,c){var d=a.attributes.mtmid;d?d=d.value:a.setAttribute("mtmid",d=B());la(b,d);c!=b&&la(c,d);return d},tb=function(a){var b=fa[a];if(b)return b[0];if(Ga!=C(a)&&!U(a)){if(N(a))return!0;for(var b=r.scripts,c={},d,e=b.length-1;0<=e;e--){var h=b[e];if(d=h.src){var k=C(d);if(d==a||k==a)return sb(h,d,k);z.href=d;var f=z.pathname;1<f.length&&(c[f]=c[f]?1:h)}}z.href=a;if((c=c[z.pathname])&&1!==c)return d=c.src,sb(c,d,
C(d));for(var c=r.querySelectorAll("iframe"),f=0,g=c.length;f!=g;f++){var K=c[f],m=K.getAttribute("mtmid");if(m)try{var M=K.contentWindow.__mtm_tags;M&&(M=M._getProfilerData);b=K.contentDocument.scripts;for(e=b.length-1;0<=e;e--)if(h=b[e],d=h.src){var l=h.getAttribute("mtmid");l||M||h.setAttribute("mtmid",l=B());if(l&&(k=C(d),d==a||k==a)){var s=pa[m];s||(pa[m]=s={});return s[l]||(s[l]=B())}}}catch(p){}}}},rc=function(a,b,c){try{if(!b.stack)try{throw b;}catch(d){b=d}if(!b.stack)return}catch(e){return}b=
b.stack.split("\n");var h=0,k=b.length;if(k&&(/^\s*Error\s*/.test(b[0])&&(h=1),/^\s*at\s+Error[\s\(]/.test(b[h])&&h++,k>h)){var f,g=/^\s*at /.test(b[h])?/[\( ]((https?|resource):.*?):\d+(?::\d+)?\)?\s*$/:/@((https?|resource):.*?):\d+:\d+\s*$/;if(b[h].match(g)){var K=location.href,m=C(location.href);for(!c&&2<=k-h&&(h+=2);h!=k;h++)if((c=b[h].match(g))&&c[1]!=K&&c[1]!=m){if(c=tb(c[1]))return!0===c?null:c}else if(!f){if(a&&!a.src&&(f=a.getAttribute("mtmparent"))&&/^\d+$/.test(f))return a.getAttribute("mtmid");
f=1}}}},Ka=function(a){return a&&!U(a)&&!N(a)},ub=function(a){var b=a.attributes,c=b.mtmid;if(c)return c.value;if(Ka(a.src))c=B();else if(c=b.mtmparent)c=c.value;if(c)return a.setAttribute("mtmid",c),c},E=I.getExecutionParent=function(a,b){var c=r.currentScript;if(!c||!(c==a||c.src&&N(c.src)))return c=rc(c,b||Error(),b)||r.__mtm_currentScript||c&&ub(c),a&&c&&a.setAttribute("mtmparent",c),c};I.getNonStackParent=function(){var a=r.currentScript;if(!(a&&a.src&&N(a.src)))return r.__mtm_currentScript||
a&&ub(a)};var S=function(a,b,c){c||(c={});c.type=a;c.node=b;Za&&Za("tag","_p",c)},sa=function(a,b,c,d){a.__mtmeh=1;d||a.setAttribute("mtmid",b);S("create",b);ra.call(a,"load",La);ra.call(a,"error",Ma);Ea.push([a,"load",La],[a,"error",Ma]);c&&(ra.call(a,"afterscriptexecute",Na),Ea.push([a,"afterscriptexecute",Na]))},vb=function(a,b){Y(a,b);var c=function(){Y(a,b)||setTimeout(function(){setTimeout(function(){Y(a,b)},1)},1);a.removeEventListener("load",c)};a.addEventListener("load",c)},wb=function(a){if(1==
a.nodeType&&a!=ma){var b=a.childNodes;if(b)for(var c=0,d=b.length;c!=d;c++)wb(b[c]);var e=a.nodeName.toUpperCase(),b=ba[e],h=a.attributes,k;k=(k=h.mtmparent)&&k.value;d=function(){if(!a.__mtmprv){var b=Ja(a,e)?32:0;b&&k&&v(b,ga[k]||k);a.__mtmprv=1;return b}};if(b){if(Fa(e,a)){var f=h.mtmid;if(a.__mtmpr)f&&(d=d())&&v(d,a.__mtmlmid||f.value);else if(a.__mtmpr=1,k||ja){var g=(c="SCRIPT"==e)&&a.src;if(c&&!Ka(g)){if(g||a.textContent)k&&(f&&f.value!=k&&(ab(k,f.value),S("merge",k,{oldNode:f.value})),a.setAttribute("mtmid",
k)),g||S("load",k,{target:a})}else{f?(f=f.value,c||a.__mtmeh||sa(a,f,0,1)):sa(a,f=B(),c);var K;b.forEach(function(b){var c=h[b]&&h[b].value,d="IFRAME"==e;if(c||d){var g=!c||U(c);if(!g||d)K=1,b={ty:e,t:{s:D()}},c&&(b.s=X(c)),d&&(b.el=a),g&&(b.loc=1),(c=jc[e])&&(d=h.type&&h.type.value)&&(d=lb(d))&&0>c.indexOf(d)&&mb(b,d),Y(a,b),Da(b,f,k)}});d=d();K&&(!k&&(c&&!h.async&&h.src||"LINK"==e&&h.rel&&"stylesheet"==h.rel.value.toLowerCase()||"STYLE"==e&&a.innerText&&a.innerText.match(/\b@import[\s'"]/))&&(d=
O(d||0,1)),d&&v(d,f));h[b[0]]||S("load",f,{target:a})}}}}else d()}};(new qc(function(a){g.__mtm_spy&&a.forEach(function(a){if(a=a.addedNodes)for(var c=0,d=a.length;c!=d;c++)wb(a[c])})})).observe(r,{childList:!0,subtree:!0});var ta=function(a){var b=new URL(a);a=ka(a).replace(/\/[^\/]+$/,"");return b.protocol+"//"+a+"/standalone-profiler-iframe.js"}(r.currentScript.src),Oa="<script src='"+ta+"'>\x3c/script>",xb=function(a){a=a.scripts;for(var b=0,c=a.length;b!=c;b++)if(a[b].src==ta)return 1},sc=function(a){var b=
a.open;a.open=function(){b.call(this);xb(this)||this.write("<body><script src='"+ta+"'>\x3c/script>")}},P=ac.prototype;["insertBefore","appendChild"].forEach(function(a){var b=P[a];P[a]=function(a){var d=g.__mtm_spy&&a&&1==a.nodeType;d&&E(a);var e=b.apply(this,arguments);if(T&&d&&"IFRAME"==a.tagName.toUpperCase()&&!a.getAttribute("src")){var h=function(a){var b=a.createElement("SCRIPT");b.src=ta;a.documentElement.appendChild(b);sc(a)};try{var k=a.contentDocument;k&&h(k)}catch(f){}p.setTimeout(function(){try{var b=
a.contentDocument;b&&!xb(b)&&h(b)}catch(d){}},1)}return e}});var ca=function(a,b,c,d,e,h){a=X(a);if(!U(a)&&!N(a))return b={ty:b,t:{s:D()},s:a},(c="string"==typeof c?c.toUpperCase():0)&&"GET"!=c&&(b.m=c),e&&(b.t.e=b.t.s,b.t.s=e),d&&(-3!=d&&200!=d&&(300>d||399<d)&&(b.d=d),(100>d||399<d)&&1223!=d&&(b.t.e=b.t.r=b.t.s,b.j=1)),c=B(),Da(b,c,h||E()),c};try{if(J){var yb=J.setResourceTimingBufferSize||J.webkitSetResourceTimingBufferSize;yb&&yb.call(J,2E3)}}catch(bc){}try{15<Error.stackTraceLimit||(Error.stackTraceLimit=
15)}catch(Ic){}var Pa,zb;if(t.defineProperty&&r.__lookupGetter__&&r.__lookupSetter__){var Ab=r.__lookupGetter__("cookie");if(Ab){var tc=r.__lookupSetter__("cookie");t.defineProperty(r,"cookie",{enumerable:!0,configurable:!0,get:function(){var a=Ab.call(r);g.__mtm_spy&&v(4);return a},set:function(a){if(g.__mtm_spy){var b=v(8);if(b){var c=a.indexOf("=");0<c&&(c=a.substring(0,c).trim(),c.length&&(b.k?0>b.k.indexOf(c)&&b.k.push(c):b.k=[c]))}}tc.call(r,a)}});zb=1}for(var uc in cb)(function(a){var b=gc[a],
c=cb[a],d=c[0];c.forEach(function(c,h){if(c&&(!h||c.prototype!=d.prototype)){var k=c.prototype;ba[a].forEach(function(c){var d=k.__lookupSetter__(c);if(d){var e=k.__lookupGetter__(c);k.__defineSetter__(c,function(c){if(g.__mtm_spy&&c&&(b||this.__mtmpr&&this.parentNode&&r.contains(this))&&Fa(a,this)){var e=ca(c,a);this.__mtmpr=1;(this.__mtmlmid=e)&&this.parentNode&&r.contains(this)&&Ja(this,a)&&(v(32,e),vb(this,A[e]))}d.call(this,c)});k.__defineGetter__(c,e)}})}})})(uc);if(g.HTMLIFrameElement){var ua=
HTMLIFrameElement.prototype,Bb=ua.__lookupSetter__("src");if(Bb){var vc=ua.__lookupGetter__("src");ua.__defineSetter__("src",function(a){if(g.__mtm_spy&&"IFRAME"==this.tagName.toUpperCase()&&a)if(T&&"javascript:"==a.substring(0,11).toLowerCase())a='javascript:"'+Oa+'"+eval("'+a.substring(11).replace(/(["\\])/g,"\\$1")+'")';else if(T&&"data:text/html"==a.substring(0,14))","==a.charAt(14)?a="data:text/html,"+encodeURIComponent(Oa)+a.substring(15):";base64,"==a.substring(14,22)&&(a="data:text/html;base64,"+
encodeURIComponent(btoa(Oa+atob(decodeURIComponent(a.substring(22))))));else if(r.contains(this)){var b=ca(a,"IFRAME");b&&Ja(this,"IFRAME")&&(v(32,b),vb(this,A[b]));this.__mtmll=a}Bb.call(this,a)});ua.__defineGetter__("src",vc)}}if(g.HTMLScriptElement){var va=HTMLScriptElement.prototype,Cb=va.__lookupSetter__("src");if(Cb){var wc=va.__lookupGetter__("src");va.__defineSetter__("src",function(a){if(g.__mtm_spy&&a&&this.__mtmpr&&!this.src&&!this.textContent&&this.parentNode){var b=this.getAttribute("mtmparent"),
c=this.getAttribute("mtmid"),d=X(a);Ka(d)?(c||sa(this,c=B(),1),d={ty:"SCRIPT",t:{s:D()},s:d},Da(d,c,b)):b&&(c&&c!=b&&(ab(b,c),S("merge",b,{oldNode:c})),this.setAttribute("mtmid",b))}Cb.call(this,a)});va.__defineGetter__("src",wc)}}var Qa=P.__lookupSetter__("innerHTML");if(Qa){p.innerHTMLSetter=function(a,b){Qa.call(a,b)};var xc=P.__lookupGetter__("innerHTML");P.__defineSetter__("innerHTML",function(a){Qa.call(this,Pa(a))});P.__defineGetter__("innerHTML",xc)}var Ra=function(a){if(a){var b=a.lastIndexOf("."),
c=a.lastIndexOf("[");if(0>b||c>b)b=c;0<=b&&(a=a.substring(b+1));return fc[a.toLowerCase().replace(/[^a-z]/g,"")]}},Db=function(a){if(a){a=a.toLowerCase().replace(/[^a-z]+/g," ");var b=a.length,c;for(c in bb){var d=c.length,e=a.indexOf(c);if(!(0>e||0<e&&" "!=a.charAt(e-1))&&(e+=d,e==b||" "==a.charAt(e)))return bb[c]}}},Eb=g.HTMLInputElement;if(Eb){var Fb=Eb.prototype;["value","valueAsNumber","valueAsDate"].forEach(function(a){var b=Fb.__lookupGetter__(a);b&&Fb.__defineGetter__(a,function(){if(g.__mtm_spy){var a=
-1;"TEXTAREA"!=this.tagName.toUpperCase()&&(a=ec[this.type.toLowerCase()]);var d;if(a)if(0<a)d=a;else{d=this.id;var e;if(d)try{e=(this.form||r).querySelector('label[for="'+d+'"]')}catch(h){}e&&(e=e.innerText);d=this.placeholder;d=Ra(this.name)||Ra(e)||Ra(d)||Db(e)||Db(d)}d&&(e=E())&&(e=G(e),e.y?0>e.y.indexOf(d)&&e.y.push(d):e.y=[d])}return b.call(this)})})}}p.innerHTMLSetter||(p.innerHTMLSetter=function(a,b){a.innerHTML=b});zb||q(O(4,8));var l=function(a,b,c){var d,e=function(){g.__mtm_spy&&v(c);
return d.call(this)};if(t.getOwnPropertyDescriptor&&t.getPrototypeOf){var h=t.getPrototypeOf(a),k=h,f;h&&(f=t.getOwnPropertyDescriptor(h,b));f||(f=t.getOwnPropertyDescriptor(h=a,b));if(f&&f.configurable){d=f.get;if(!d&&f.value){var Z=f.value;delete f.value;f.writable&&(f.set=function(a){Z=a});delete f.writable;d=function(){return Z}}f.get=e;try{t.defineProperty(h,b,f);return}catch(l){if(h!=k)try{return t.defineProperty(k,b,f),t.getOwnPropertyDescriptor(h,b)?1:0}catch(m){}}}}if(a.__lookupGetter__&&
(d=a.__lookupGetter__(b))){h=a.__lookupSetter__(b);a.__defineGetter__(b,e);h&&a.__defineSetter(b,h);return}return 1},Q=function(a,b,c){var d=a[b];if(d){var e=c;"function"!=typeof c&&(e=function(){v(c)});var h=function(){g.__mtm_spy&&e();return d.apply(this,arguments)};try{a[b]=h}catch(k){}if(a[b]!=h)return 1}};l(n,"platform",8192)&&q(8192);l(n,"doNotTrack",65536)&&q(65536);l(n,"userAgent",1073741824)&&q(1073741824);l(n,"language",4294967296)&l(n,"languages",4294967296)&&q(4294967296);l(y,"colorDepth",
16384)&l(y,"pixelDepth",16384)&&q(16384);l(y,"width",64)&l(y,"height",64)&l(y,"availLeft",64)&l(y,"availTop",64)&l(y,"availWidth",64)&l(y,"availHeight",64)&&q(64);l(y,"left",2147483648)&l(y,"top",2147483648)&&q(2147483648);l(n,"hardwareConcurrency",32768)&l(n,"cpuClass",32768)&l(n,"oscpu",32768)&&q(32768);l(n,"battery",131072)&Q(n,"getBattery",131072)&&q(131072);var Sa=n.plugins;Sa&&(l(Sa,"Shockwave Flash",2097152)&&q(2097152),l(Sa,"Silverlight Plug-In",4194304)&&q(4194304),l(n,"plugins",4096)&&q(4096));
var da={};Q(g,"open",function(){var a=E();a&&(da[a]=p.setTimeout(function(){da[a]&&(delete da[a],v(33554432,a))},500))})&Q(g,"focus",function(){for(var a in da)v(268435456,a),clearTimeout(da[a]);da={}})&&q(O(33554432,268435456));Q(g,"alert",67108864)&Q(g,"confirm",67108864)&Q(g,"prompt",67108864)&&q(67108864);Q(g,"openDatabase",524288)&&q(524288);l(g,"indexedDB",262144)&&q(262144);var Gb=g.HTMLCanvasElement;if(Gb){var wa=Gb.prototype;if(wa){var Hb=wa.getContext;if(Hb){var yc={webgl:1,"experimental-webgl":1,
webgl2:1,"experimental-webgl2":1};wa.getContext=function(a){g.__mtm_spy&&a&&yc[a]&&v(16777216);return Hb.apply(this,arguments)}}}l(wa,"toDataURL",536870912)&&q(536870912)}var Ib=Date.prototype;Ib&&Q(Ib,"getTimezoneOffset",1048576);var Jb=function(a,b){var c=A[a],d=b("content-type");d&&(d=lb(d))&&mb(c,d);d=b("content-length");null==d||isNaN(d=parseInt(d,10))||(c.l=d)},xa=XMLHttpRequest.prototype,zc=xa.open;xa.open=function(a,b){this.__mtm_method=a;this.__mtm_url=b;return zc.apply(this,arguments)};
var Ac=xa.send;xa.send=function(){var a=this,b=a.__mtm_url;if(g.__mtm_spy&&b){var c=ca(b,"AJAX",this.__mtm_method),d=function(a){if(g.__mtm_spy){var b=G(c);-3!=a&&200!=a&&(300>a||399<a)&&(b.d=a);(100>a||399<a)&&1223!=a&&(b.tr=b.te=D(),b.j=1)}};a.addEventListener("load",function(){if(g.__mtm_spy){var b=a.getAllResponseHeaders();Jb(c,function(a){return(a=b.match(RegExp("(?:^|\n)"+a+"\\s*:\\s*(.*)","i")))&&a[1]});d(a.status)}});a.addEventListener("error",function(){d(-1)});a.addEventListener("abort",
function(){d(-2)})}return Ac.apply(a,arguments)};var Ta=n.sendBeacon;Ta&&(p.sendBeacon=function(){return Ta.apply(n,arguments)},n.sendBeacon=function(a){var b=Ta.apply(this,arguments);g.__mtm_spy&&b&&a&&ca(a,"BEACON","POST");return b});if(g.Proxy&&"function"==typeof Proxy&&g.__defineGetter__){var Kb=function(a){a()},ha={key:0,getItem:0,setItem:1,removeItem:1,clear:1},Bc=I.webStorageHooks={},Cc=function(a,b,c,d,e){var h=ha[c],k=h?e:d,f=a[c];return function(){var c=b[h];if(c&&!c())return null;g.__mtm_spy&&
v(k);return f.apply(a,arguments)}},Lb=function(a,b,c){var d=Bc[a]=[0,0];a+="Storage";var e=g[a],h={},k;for(k in ha)h[k]=Cc(e,d,k,b,c);k=function(a,b){if("undefined"==typeof ha[b]){var e=d[1];if(e&&!e())return!0;g.__mtm_spy&&v(c);delete a[b]}return!0};var f=new Proxy(e,{"delete":k,deleteProperty:k,ownKeys:function(){var a=d[0];if(a&&!a())return[];g.__mtm_spy&&v(b);return t.getOwnPropertyNames(e)},apply:Kb,construct:Kb,get:function(a,c){if("undefined"==typeof ha[c]){var f=d[0];if(f&&!f())return;g.__mtm_spy&&
v(b);return e[c]}return h[c]},set:function(a,b,f){if("undefined"==typeof ha[b]){if((a=d[1])&&!a())return;g.__mtm_spy&&v(c);e[b]=f}return!0}});g.__defineGetter__(a,function(){return f})};try{Lb("local",128,256)}catch(Mb){"SecurityError"!=Mb.name&&console.error("Cannot override localstorage",Mb)}try{Lb("session",512,1024)}catch(Nb){"SecurityError"!=Nb.name&&console.error("Cannot override sessionstorage",Nb)}}else q(O(O(128,256),O(512,1024)));if(g.Promise){var ia=Promise.prototype,Ua;if(ia){if(Ua=ia.then)ia.then=
function(a,b){if(a||b){var c=E();c&&(a&&(a=W(a,0,c)),b&&(b=W(b,0,c)))}return Ua.call(this,a,b)};var Ob=ia["catch"];Ob&&(ia["catch"]=function(a){return Ob.call(this,a?W(a):a)})}var Pb=g.fetch;Pb&&(g.fetch=function(a,b){var c=Pb.apply(this,arguments);if(!g.__mtm_spy)return c;var d,e;g.Request&&a instanceof Request?(d=a.url,e=a.method):(d=a,e=b&&b.method);var h=E(),k=D();return(Ua||c.then).call(c,function(a){if(g.__mtm_spy){var b=ca(d,"FETCH",e,a.status||(a.ok?200:-3),k,h),c=a.headers;if(b&&c){var m=
c.get;m&&Jb(b,m.bind(c))}}return a},function(a){g.__mtm_spy&&ca(d,"FETCH",e,-1,k,h);throw a;})})}var Va=__mtm_tags.postscribe.HTMLParser("",{innerHTMLSetter:p.innerHTMLSetter});Pa=function(a){var b=g.__mtm_spy;if(b&&"string"==typeof a&&a){var c=[],d,e;for(Va.append(a);d=Va.readToken();){var h,k=0,f=d.text;b&&db[d.type]&&"SCRIPT"!=d.tagName.toUpperCase()&&(k||(h=E(),k=1),h&&(f=f.replace(/(\/?>)/," mtmparent="+h+" $1"),e=1));qa(d,h,k)&&(e=1,f=d.text);c.push(f)}e&&(a=c.join(""));Va.clear()}return a};
var Dc=P.insertAdjacentHTML;P.insertAdjacentHTML=function(a,b){return Dc.call(this,a,Pa(b))};var Wa=n.geolocation;Wa&&Q(Wa,"getCurrentPosition",16)&Q(Wa,"watchPosition",16)&&q(16);var ya,Qb,Xa;if(Ha&&g.watch){var Rb=function(a,b,c){ya=X(c);return c};g.watch("location",Rb);location.watch("href",Rb);"protocol host hostname port pathname search".split(" ").forEach(function(a){location.watch(a,function(a,c,d){z.href=location.toString();z[a]=d;ya=z.href;return d})});g.addEventListener("beforeunload",function(){Xa=
E();Qb=ya;ya=0});g.addEventListener("unload",function(){Xa&&(G(Xa).rd=Qb||!0)})}else hb=1;var La=function(a){this.removeEventListener("load",La);var b=this.__mtmlmid||this.getAttribute("mtmid"),c=this.src,d=this.tagName.toUpperCase();if(c||"IFRAME"!=d)c&&N(c)||(c=G(b),c.tr=D(a.timeStamp),"SCRIPT"!=d&&(c.te=c.tr),(a=A[b])&&Y(this,a)),S("load",b,{target:this})},Ma=function(a){this.removeEventListener("error",Ma);var b=this.__mtmlmid||this.getAttribute("mtmid"),c;if(this.src&&N(this.src))c="load";else{c=
"error";var d=G(b);d.te=D(a.timeStamp);d.j=1;d.tr||(d.tr=d.te)}S(c,b,{target:this})},Na=function(a){this.src&&N(this.src)||(G(this.getAttribute("mtmid")).te=D(a.timeStamp),this.removeEventListener("afterscriptexecute",Na))},Sb=function(a,b,c,d){if(a){var e=G(a);e.e||(e.e=[]);b={t:D(),m:b};c&&(b.i=c);d&&(b.d=1);e.e.push(b);S("error",a)}};g.addEventListener("error",function(a){if(g.__mtm_spy){var b,c,d,e=a.error;if(e){try{if(e.__mtmpr)return}catch(h){}try{c=e.message,d=e.name}catch(k){}b=E(0,e)}c||
(c=a.message||"Unknown error");if(!b&&(a=a.filename)&&!0===(b=tb(a)))return;Sb(b,c,d)}});var Tb=function(a,b,c){b=b.apply(this,c);a=a.toUpperCase();g.__mtm_spy&&(c=E(b),ba[a]?(c=B(),G(c).ts=D(),sa(b,c,"SCRIPT"==a)):c&&"CANVAS"==a&&v(8388608,c));return b},za=$b.prototype,Ec=za.createElement;za.createElement=function(a){return Tb.call(this,a,Ec,arguments)};var Fc=za.createElementNS;za.createElementNS=function(a,b){return Tb.call(this,b,Fc,arguments)};var W=function(a,b,c){if(c=c||E()){var d=a;a=function(){r.__mtm_currentScript=
c;var a,b;try{if(null!=d){var k=typeof d;if("object"==k&&"function"==typeof d.handleEvent)b=d.handleEvent.apply(d,arguments);else if("string"==k)b=(new Function(d)).apply(this,arguments);else if("function"==k)b=d.apply(this,arguments);else throw new TypeError("The callback is neither a function nor an object with 'handleEvent' property");}}catch(f){a=f;a.__mtmpr=1;var k="Unknown error",g;try{k=a.message,g=a.name}catch(l){}Sb(E(0,a)||c,k,g,1)}r.__mtm_currentScript=null;if(a)throw a;return b}}return a},
Ub=function(a,b){var c=new Map,d=a.addEventListener;a.addEventListener=function(a,e,f){var l=e;g.__mtm_spy&&b(a)&&c.set(e,l=W(e));return d.call(this,a,l,f)};var e=a.removeEventListener;a.removeEventListener=function(a,d,f){var g=d;if(b(a)){var l=c.get(d);l&&(g=l,c["delete"](d))}return e.call(this,a,g,f)};return[d,e]},Vb=Ub(r,function(a){return"DOMContentLoaded"==a}),Wb=Ub(g,function(a){return"load"==a});if(t.getOwnPropertyDescriptor){try{var Aa=t.getOwnPropertyDescriptor(g,"onload");if(!Aa||Aa.configurable){var Gc=
g.onload,Xb=Aa&&Aa.set;g.onload=null;var Ba,Yb;t.defineProperty(g,"onload",{configurable:!0,enumerable:!0,get:function(){return Ba},set:function(a){var b=a&&g.__mtm_spy?W(a):a;Xb?(Ba=a,Xb.call(this,b)):(Ba&&Wb[1].call(g,"load",Yb),(Ba=a)&&Wb[0].call(g,"load",b));Yb=b}});g.onload=Gc}}catch(Jc){}if(g.HTMLElement){var Zb=HTMLElement.prototype;["onload","onerror"].forEach(function(a){try{var b=t.getOwnPropertyDescriptor(Zb,a);if(b&&b.configurable){var c=b.get,d=b.set;p[a+"Setter"]=function(a,b){d.call(a,
b)};var e="__mtm_"+a;t.defineProperty(Zb,a,{configurable:!0,enumerable:!0,get:function(){return this[e]||c.call(this)},set:function(a){this[e]=a;d.call(this,a&&g.__mtm_spy?W(a):a)}})}}catch(h){}})}}p.onloadSetter||(p.onloadSetter=function(a,b){a.onload=b},p.onerrorSetter=function(a,b){a.onerror=b});var Hc={load:1,error:1,abort:1,submit:1,click:1,mousedown:1,mouseup:1,blur:1,focus:1,change:1,input:1,keydown:1,keypress:1,keyup:1},ra=P.addEventListener;P.addEventListener=function(a,b,c){g.__mtm_spy&&
Hc[a]&&(b=W(b,1));return ra.call(this,a,b,c)};p.documentAddEventListener=Vb[0];p.documentRemoveEventListener=Vb[1];["setTimeout","setInterval"].forEach(function(a){var b=g[a];p[a]||(p[a]=function(){return b.apply(g,arguments)});var c="setInterval"==a;g[a]=function(){if(g.__mtm_spy){var a=Array.prototype.slice.call(arguments);a[0]=W(a[0],c);return b.apply(this,a)}return b.apply(this,arguments)}});return function(a){if(!A)return{d:[]};Ea.forEach(function(a){a[0].removeEventListener(a[1],a[2])});var b=
[],c,d,e,h=J&&J.getEntriesByName,k;J&&(k=J.timing);if(ea)for(var f in ea)if(e=ea[f],!e.fake){d={tid:e.id,ty:"HTML",t:{}};0<e.os?d.t.s=Math.round(e.os):e.s>L&&(d.t.s=e.s-L);e.oe>=e.os?d.t.e=Math.round(e.oe):e.s&&e.e>=e.s&&(d.t.e=e.e-L);e.varn&&(d.tv=e.varn);var l=e.err;if(l){var p=l.m,m=l.t>=(e.s||e.os)?{m:p,t:Math.round(l.t)-(e.s?L:0)}:{m:p},q=d,v,s=l.url;if(s){var n=fa[s=X(s)];if(n){l=n[0];if(1!=n.length)for(c in A)if(n=A[c],"SCRIPT"==n.ty&&n.s==s&&lc(n)==f){l=c;break}if(l=R[l])if(s=l.e){v=1;for(var t,
l=0,n=s.length;l!=n;l++)if(s[l].m==p){t=1;s[l].p=1;break}t||(m.p=1,s.push(m))}else q=l}}v||(q.e=[m])}if(e=e.cs){if(e.t){for(c in e.t)d.t[c]=e.t[c];delete e.t}for(c in e)d[c]=e[c]}b.push(d);A[f]=d}f={};var D={};v=[];var u={},w={},E=function(a,b){for(var c=0,d=a.length;c!=d;c++){var e=a[c],f=e.c;f&&E(f,b);var g=e.key;if(g){delete e.key;var h=b[g];if(h){var k=u[h];k?e.c=f?f.concat(k):k:w[h]=e;delete b[g]}}}};t=function(a){return oa(a)||w[a]};e=function(a,b){if(h){var c=b,d=J.getEntriesByName(b);d&&d.length||
(d=J.getEntriesByName(c=C(b)));if(d&&d.length){var e;if(1==d.length||a.t.s)if(a.t.s)for(var f=Number.POSITIVE_INFINITY,g=0;g!=d.length;g++){var k;k=d[g];var l=a,m=Math.abs(k.startTime-l.t.s);l.t.r&&(m+=Math.abs(k.responseEnd-l.t.r));k=m;k<f&&(e=d[g],f=k)}else e=d[0];else e=void 0;a.t.s=Math.round(e&&e.startTime||a.t.s||0);a.t.r=Math.round(e&&e.responseEnd||a.t.r||0);if("SCRIPT"==a.ty){if(!a.t.e||a.t.e<a.t.r)a.t.e=a.t.r}else a.t.e=a.t.r}D[c]=1}};var H=function(a,b){var c=R[a],d=0;if(c){var e=c.f;e&&
(b.f=e);if(e=c.e){var f=0;e.forEach(function(a){a.d&&f++});f?e=e.filter(function(a){if(!a.d&&!a.p&&f)return f--,!1;delete a.d;delete a.p;return!0}):e.forEach(function(a){delete a.p});var d=1,g=ob(e);(e=b.e)&&e.forEach(function(a){var b=a.m;if(!g["--"+b]){var b=jb(b),c=(b[0]||"")+"--"+b[1];g[c]||(a={m:b[1],t:a.t,c:1},b[0]&&(a.i=b[0]),g[c]=a)}});b.e=pb(g)}c.j&&(b.j=1);c.d&&(b.d=c.d);if(e=c.k)b.k="undefined"!==typeof enableHeavyStatistics&&enableHeavyStatistics?e:5<e.length?e.slice(0,5):e;if(e=c.r)b.r=
pb(ob(e));if(e=c.rd)b.z=e;if(e=c.y)e.sort(),b.y=e;if(!b.tid){var h=c.ts;0<h&&(b.t.s=h);(e=c.tr)&&e>=h&&(b.t.r=e);(e=c.te)&&e>=h&&(b.t.e=e)}}!d&&b.e&&b.e.forEach(function(a){var b=jb(a.m);a.m=b[1];b[0]&&(a.i=b[0])})},p=function(a,b){a.splice.apply(a,[-1,1].concat(b.c||[]))};for(c in A){d=A[c];m=d.s;q=d.virt;delete d.virt;if(m){if(N(d.s))continue;q||(f[m]=1)}a&&(d.key=c);H(c,d);m&&!q&&e(d,m);if(!d.tid&&(q=m=null,(l=d.pr)?((m=t(l))?(q=m.c,q||(m.c=q=[]),q.push(d),"SCRIPT"==d.ty&&(m.f=O(m.f||0,2))):(m=
u[l])?m.push(d):u[l]=[d],delete d.pr):ja&&(q=b,b.push(d)),"IFRAME"==d.ty)){s=d.el;delete d.el;if(s){var n=pa[c],x=0,z=0;try{if(z=s.contentWindow){var B=z.location+""||"",G=C(B);if(G!=C(location.href)&&"about:blank"!=G&&G!=C(s.__mtmll||d.s||"")){var x=1,y=[];gb(y,s,n);if(B&&!U(B)){f[B]=1;var T={ty:"IFRAME",s:B,t:{}};y.length&&(T.c=y);d.f&&(T.f=d.f);e(T,B);d.c=[T]}else d.c=y}}}catch(P){}if(!x){x=null;try{z&&(x=z.__mtm_tags)}catch(Q){}z=null;y=L;if(x&&x._getProfilerData)x=x._getProfilerData(n),(z=x.d).length&&
(y=x.ti.re,x.n&&($=mc(z,x.n,$)));else if(z=[],gb(z,s,n),z.length)try{var I=s.contentWindow.performance;I&&(I=I.timing)&&(y=I.navigationStart)}catch(S){}nb(z,y-L);d.c=z}n&&d.c&&E(d.c,n);v.push(s)}d.loc||!d.s||U(d.s)?(delete d.loc,q?(p(q,d),m&&m.c&&!m.c.length&&delete m.c):!m&&u[l]&&0<=u[l].indexOf(d)?p(u[l],d):m&&m.indexOf&&0<=m.indexOf(d)&&p(m,d)):d.c&&!d.c.length&&delete d.c}}ja&&(kc(b,r.documentElement,J,f,D,v,t,function(a,b){var c=u[a];c&&(b.c=c);H(a,b)}),nc(b,u),ib(b));b=qb(b);g.__mtm_spy||(u=
pa=ga=R=fa=A=0);a={d:b,h:32};na&&(a.f=na);hb&&(a.z=1);$.length&&(a.n=$);if(k){a.ti={re:k.navigationStart,dl:k.domLoading-L};if(b=k.domInteractive)a.ti.di=b-L;if(b=k.loadEventStart)a.ti.ls=b-L}else a.ti={re:L};return a}};__mtm_tags._profLogger=function(n){g.__mtm_data_sent=0;var r=__mtm_tags._overriddenAPIs,t=function(p){if(!g.__mtm_data_sent&&g.__mtm){g.__mtm_spy--;g.__mtm_data_sent=1;var t=n();t.c=g.__mtm[0];console.log(t);var t=JSON.stringify(t),y=r.sendBeacon;if(!y||!y("//crow.mezzobit.com/",t))try{var C=
new XMLHttpRequest;C.open("POST","//crow.mezzobit.com/",p);C.send(t)}catch(ka){}}},y=function(){t(!1)};g.addEventListener?g.addEventListener("unload",y):g.attachEvent("onunload",y);r.setTimeout(function(){t(!0)},4E4)};__mtm_proc(__mtm_tags)})(window,document,navigator,screen,Object,window.Document,Element,Image);
