//# sourceMappingURL=mtm.js.map
(function(m,n,S,X,cb,B,y,ka,w){function Y(a){return B.isArray?B.isArray(a):a instanceof B}if(m.opener&&"mzbtVisualTagPlacerWindow"==m.name.substring(0,25)){var wa=n.createElement("script");wa.src="//s3.amazonaws.com/mbcdn/scripts/visual-tag-placer/app.js";wa.id="mzbtScript";wa.className="fromMtm";n.getElementsByTagName("head")[0].appendChild(wa)}else{m.__mtm_data=m.__mtm_data||[];m.__mtm_spy=m.__mtm_spy||0;var la=m.performance,db=function(){var a=S.userAgent;if(n.currentScript&&m.Map&&(m.MutationObserver||
m.WebKitMutationObserver)&&!/Edge\/\d/i.test(a)){if(a=a.match(/\bFirefox\/([\d\.]+)/i))if(a=parseFloat(a[1]),!(38<=a))return;if(m.Object&&m.Element&&cb.getOwnPropertyDescriptor&&Element.prototype)return(a=cb.getOwnPropertyDescriptor(Element.prototype,"innerHTML"))&&a.configurable}},Nb=function(){return{ti:{},d:[]}};n.createElement("a");var ma=la&&la.now?function(){return la.now()}:function(){return(new y).getTime()-m.__mtm_start},Ob=String((new y).getTime())+"."+Math.random(),P={},eb=function(a){return a.replace(/&(?!\w+;)/g,
"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")},na=function(a){return a.replace(/[\\'"]/g,"\\$&").replace(/<\//g,"<\\/").replace(/\x3c!--/g,"<\\!--").replace(/\/>/g,"/\\>")},Pb=/<script[>\s\r\n][.\r\n]*?<\/script\b/gi,Qb=/<script[>\s\r\n]\b[.\r\n]*?>/i,fb=function(a){return a.replace(/\\([\!"#$%&'\(\)\*\+,\.\/:;<=>\?\@\[\\\]\^`\{\|\}~])/g,"$1")},Ia=function(a){a+="=";for(var b=n.cookie.split(/\s*;\s*/),c=0,d=b.length;c<d;c++){var f=b[c];if(0==f.indexOf(a))return unescape(f.substring(a.length))}},
gb="indexOf"in B.prototype?B.prototype.indexOf:function(a){for(var b=0,c=this.length;b!=c;b++)if(this[b]===a)return b;return-1},Rb=n.getElementsByClassName?function(a,b){return a.getElementsByClassName(b)}:function(a,b){for(var c=a.getElementsByTagName("*"),d=[],f=new ka("(?:^|\\b)"+b+"(?:\\b|$)"),e=0,g=c.length;e<g;e++)f.test(c[e].className)&&d.push(c[e]);return d},Ja=n.querySelector?function(a,b){if(b)return n.querySelectorAll(a);var c=n.querySelector(a);return c?[c]:[]}:function(a,b){var c=n.body,
d=a.match(/(?:[^#\\]|\\.)*#((?:[^#\.\s\\]|\\[^\s])+).*?\s(.*$)/g),f=d&&d[1];f&&(c=c.getElementById(fb(f)),a=d[2].trim());for(var f="string"===typeof a?a:a.split(/\s+/),e=[c],g=f.length,h=0;h<g;h++)if(d=f[h].match(/^([^\.])?(\..+$|$)/g)){var k=d[1],d=d[2];k&&(k=k.toLowerCase());if(d){if(d=fb(d).replace(/\./g," "),e=c.getElementsByClassName(d),k){for(var d=[],l=0,r=e.length;l!=r;l++){var c=e[l],p=c.tagName;p&&p.toLowerCase()==k&&d.push(c)}e=d}}else k&&(e=c.getElementsByTagName(k));if(1===e.length)break}return e},
Sb="CSS1Compat"==n.compatMode,hb=function(){var a=m.pageYOffset;return a===w?(Sb?n.documentElement:n.body).scrollTop:a},Tb=m.requestAnimationFrame||m.webkitRequestAnimationFrame||m.mozRequestAnimationFrame||function(a){__mtm_tags._overriddenAPIs.setTimeout(a,1E3/60)},Ub={},xa=function(a){return Ub[a]||"//"+__mtm[1]+"/module-"+a+".js"};m.__mtm_load=function(a,b,c){if(b){var d;if("undefined"!=typeof XMLHttpRequest)d=new XMLHttpRequest;else try{d=new ActiveXObject("Msxml2.XMLHTTP")}catch(f){try{d=new ActiveXObject("Microsoft.XMLHTTP")}catch(e){return}}d.open("GET",
a,!0);d.onreadystatechange=function(){if(4==d.readyState&&200==d.status){var a=n.createElement("div");__mtm_tags._overriddenAPIs.innerHTMLSetter(a,d.responseText);n.getElementsByTagName("body")[0].appendChild(a)}};d.send(null)}else b=n.createElement("script"),b.async=1,c&&(b.onerror=c,b.onreadystatechange=function(){var a=this.readyState;"complete"!=a&&"loaded"!=a||__mtm_tags._overriddenAPIs.setTimeout(c,0)}),b.src=a,a=n.getElementsByTagName("script")[0],(a.parentNode||n.body).insertBefore(b,a)};
for(var oa={},La=function(a,b,c){if(oa[b])oa[b].push(c);else{oa[b]=[c];var d=function(a,c){var d=oa[b];if(d){delete oa[b];for(var h=0,k=d.length;h!=k;h++)d[h](a,c)}};Ka[b]=function(a){d(w,a)};__mtm_load(a,0,function(a){d(a)})}},ca=function(a,b,c){function d(){++f>=g&&c()}if(a&&a.length)for(var f=0,e=0,g=a.length;e<g;e++)b(a[e],d);else c()},Vb=function(a,b,c){ca(a,function(a,f){b(a,function(a){a||(c(),c=function(){});f()})},function(){c(1)})},Wb=function(a,b){Vb(a,function(a,b){a(b)},b)},Xb=(1<<32)-
1||-1,Yb=0,ib=function(a,b,c,d,f,e,g){var h=c.length,k=(h-1>>5)+1,l=new B(k);d&&(d=h&31)&&(l[k-1]=~((1<<d)-1));var r=g(l,k),p=Yb++;a=a?a.concat(p):[p];b&&(b.sel[p]=c.length);for(b=0;b<h;b++)f(a,c[b],function(a){var b=a>>5,c=1<<(a&31);return function(a,d){a!==w&&(l[b]=a?(l[b]||0)|c:(l[b]||0)&~c,d.ch[p]=1);--d.sel[p]||(d.ch[p]?r(d):e(w,d))}}(b))},jb=function(a,b,c,d,f){ib(a,b,c,1,d,f,function(a,b){return function(c){for(var d=0;d!=b;d++)if(~a[d]&Xb){f(0,c);return}f(1,c)}})},kb=function(a,b,c,d,f){ib(a,
b,c,0,d,f,function(a,b){return function(c){for(var d=0;d!=b;d++)if(a[d]){f(1,c);return}f(0,c)}})},Zb=function(a,b,c,d){jb(a,b,c,function(a,b,c){b(a,c)},d)},pa=new y,qa={},Ma={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11},lb={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6},H={},$b=function(a,b){var c=b.rules,d=b.off,f=function(a,b,c){var f=0;if("u"===b||"g"===b||"z"===b)f=0;else if("s"===b)f=d;else{if("w"!==b&&b)throw"unknown type "+b;f=-Math.ceil(c[6]-d)}f*=6E4;return new y(a.getTime()+
f)},e=function(a,b){var c=a[0],d=a[1],e=d[5],g;H[c]||(H[c]={});if(H[c][d])g=H[c][d];else{if(isNaN(d[4])){var l,h;"last"===d[4].substr(0,4)?(g=new y(y.UTC(c,Ma[d[3]]+1,1,e[0]-24,e[1],e[2],0)),l=lb[d[4].substr(4,3)],h="<="):(g=new y(y.UTC(c,Ma[d[3]],d[4].substr(5),e[0],e[1],e[2],0)),l=lb[d[4].substr(0,3)],h=d[4].substr(3,2));var k=g.getUTCDay();">="===h?g.setUTCDate(g.getUTCDate()+(l-k+(l<k?7:0))):g.setUTCDate(g.getUTCDate()+(l-k-(l>k?7:0)))}else g=new y(y.UTC(c,Ma[d[3]],d[4],e[0],e[1],e[2],0));H[c][d]=
g}b&&(g=f(g,e[4],b));return g},g=function(a,b){for(var c=[],d=0;b&&d<b.length;d++)b[d][0]<=a&&(b[d][1]>=a||b[d][0]===a&&"only"===b[d][1]||"max"===b[d][1])&&c.push([a,b[d]]);return c},h=function(a,b,c){var d,g;a.constructor!==y?(d=a[0],g=a[1],a=!c&&H[d]&&H[d][g]?H[d][g]:e(a,c)):c&&(a=f(a,"w",c));b.constructor!==y?(d=b[0],g=b[1],b=!c&&H[d]&&H[d][g]?H[d][g]:e(b,c)):c&&(b=f(b,"w",c));return Number(a)-Number(b)},k=a.getUTCFullYear(),l;l=g(k,c);l.push(a);l.sort(h);2>gb.call(l,a)&&(l=l.concat(g(k-1,c)),
l.sort(h));c=gb.call(l,a);return 1<c&&0>h(a,l[c-1],l[c-2][1])?l[c-2][1]:0<c&&c<l.length-1&&0<h(a,l[c+1],l[c-1][1])?l[c+1][1]:0===c?null:l[c-1][1]},mb=function(a,b){if(null===b)return a;var c=a.getTime(),d;for(d=b.length-1;0<=d&&!(b[d].since&&b[d].since<c);d--);var f=b[d+1];d=f.off;(f=$b(a,f))&&(d=-Math.ceil(f[6]-d));return(d=a.getTimezoneOffset()-d)?new y(c+6E4*d):a},nb=function(a){a=a.split(/[:\s-]/);return new y(a[0],parseInt(a[1],10)-1,a[2],a[3]||0,a[4]||0,a[5]||0)},ac={minute:"Minutes",hour:"Hours",
day:"Date",month:"Month",year:"FullYear",dayOfWeek:"Day"},Na=function(a,b){if(!a)return 1;var c=a.length;if(!c)return 1;for(var d=0;d!=c;d++){var f=a[d],e;a:{e=f.period;var g=b;if(e){g=g.getTime();if("string"==typeof e.from&&nb(e.from).getTime()>g){e=!1;break a}if("string"==typeof e.to&&nb(e.to).getTime()<g){e=!1;break a}}e=!0}if(e)a:{f=f.rules;e=b;if(f)b:for(g in g=void 0,f){var h=f[g],k=e["get"+ac[g]]();if("*"!=h){for(var h=h.split(/,/),l=0,r=h.length;l<r;l++){var p=h[l].split(/-/),u=parseInt(p[0],
10);if(!(u>k)){if(u==k)continue b;if(1!=p.length&&parseInt(p[1],10)>=k)continue b}}e=0;break a}}e=1}if(e)return 1}return 0},da={},I={},ea={},Oa={},ya=function(a){if($[a]){for(var b={},c=0,d=$[a].length;c!=d;c++)$[a][c](b);delete $[a]}ea[a]=1;if(d=I[a]){var b=[],c=!0,f;for(f in d)if(d=da[f])--d[1]?c=!1:(b.push([d[0],f,d[1]]),delete da[f]);b.length&&fa(b)();c&&delete I[a]}},ra={"var":{},ev:{},"":{},dom:{},tag:{}},bc=1,T=function(a,b,c,d){var f=ra[a],e=f[b];e||(__mtm_tags._overriddenAPIs.setTimeout(function(){z("",
"+",{g:a,k:b})},0),f[b]=e={sel:{},selChildren:{},cb:{}});f=bc++;e.cb[f]=[c,d];if(d){c=e.sel;var e=e.selChildren,g=d.length-1,h=d[g];c[h]?c[h]++:c[h]=1;var k=h;for(g--;0<=g;g--){var h=d[g],l=e[h];l?l[k]||(l[k]=1,c[h]++):(e[h]=l={},l[k]=1,c[h]=1);k=h}}return f},U=function(a,b,c){var d=ra[a][b],f;if(d&&(f=d.cb[c])){if(f=f[1]){var e=d.sel,g=d.selChildren,h=f.length-1,k=f[h];if(!--e[k]){delete e[k];var l=k;for(h--;!e[l]&&0<=h;h--){var k=f[h],r=g[k];r&&delete r[l];var l=0,p;for(p in r)l++;l?e[k]=l:(delete g[k],
delete e[k]);l=k}}}delete d.cb[c];for(p in d.cb)return 1;delete ra[a][b];z("","-",{g:a,k:b});return-1}},z=function(a,b,c){"ev"==a?ya(b):"tag"==a&&"l"==b.charAt(0)&&ya("-"+b.substring(1));if(a=ra[a][b]){var d;b=a.sel;var f={};for(d in b)f[d]=b[d];c={sel:f,ch:{},ev:c};a=a.cb;for(d in a)a[d][0](c)}},aa=n.addEventListener,za={},cc=1,K=function(a,b,c,d){var f=a.__mtm_eid;f||(za[a.__mtm_eid=f=cc++]=[a,{}]);var e=za[f][1],g=b+"."+f;e[b]||(f=function(a){z("dom",g,a)},e[b]=f,aa?a.addEventListener(b,f):a.attachEvent("on"+
b,f));return T("dom",g,c,d)},Q=function(a,b,c){var d=a.__mtm_eid;if(d&&0>U("dom",b+"."+d,c)){c=za[d][1];var f=c[b];aa?a.removeEventListener(b,f):a.detachEvent("on"+b,f);delete c[b];var e,g;for(g in c){e=1;break}if(!e)try{delete a.__mtm_eid,delete za[d]}catch(h){}}},Pa,ob,dc=function(){if(!ob){for(var a=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"],b=n.createElement("a"),c,d=0;5!=d;d++)if(b[c=a[d]]){Pa=c;break}ob=1}},Aa=function(a,b){dc();var c=function(a){return function(c){var d=
c.ev.target;if(Pa){if(d[Pa](b)){a(c);return}}else for(var h=Ja(b,1),k=0;k<h.length;k++)if(h[k]==d){a(c);return}a(c,1)}},d;return{listen:function(b,e){d=K(n,a,c(e),b)},stop:function(){Q(n,a,d)}}},$={},Ba=function(a){N?a():($["mtm.dom"]||($["mtm.dom"]=[]),$["mtm.dom"].push(a))},Ca={},pb=function(a,b){var c=Ca[a];if(c)c(b[a]);else return 1},ec=function(){for(var a=0,b=__mtm_data.length;a<b;a++){var c=__mtm_data[a],d;for(d in c)"event"==d?ea[c.event]=1:pb(d,c)&&(Oa[d]=c[d])}__mtm_data={push:function(a){for(var b in a)if("event"==
b){var c=a.event;c&&"string"==typeof c&&"-"!=c[0]&&"mtm."!=c.substring(0,3)&&z("ev",c)}else pb(b,a)&&(Oa[b]=a[b],z("var",b))}}},N=0,Qa=function(){z("ev","mtm.dom")},fc=function(){var a=function(){aa?(n.removeEventListener("DOMContentLoaded",b),m.removeEventListener("load",b)):(n.detachEvent("onreadystatechange",b),m.detachEvent("onload",b))},b=function(b){if(aa||"load"===b.type||"complete"===n.readyState)N=1,a(),Qa()},c=n.readyState;if(N=aa?"loading"!=c:"complete"==c)Qa();else if(aa)n.addEventListener("DOMContentLoaded",
b),m.addEventListener("load",b);else{n.attachEvent("onreadystatechange",b);m.attachEvent("onload",b);var d;try{d=null==m.frameElement&&n.documentElement}catch(f){}d&&d.doScroll&&function g(){if(!N){try{d.doScroll("left")}catch(b){return __mtm_tags._overriddenAPIs.setTimeout(g,50)}N=1;a();Qa()}}()}},qb=["resize","scroll","load"],Ra=function(a){for(var b=new B(3),c=0;3!=c;c++)b[c]=K(m,qb[c],a);return b},rb=function(a){for(var b=0;3!=b;b++)Q(m,qb[b],a[b])},gc=function(a){La("//tdi.mezzobit.com/locate",
"locate",function(b,c){var d=[];c&&(c.country&&(d.push("s"+c.country),c.region&&d.push("r"+c.country+c.region),c.city&&d.push("c"+c.country+(c.region||"")+"-"+c.city.toLowerCase())),c.postal&&d.push("p"+c.postal),c.dma&&d.push("m"+c.dma));a(d)})},sb=function(a){var b=null,c;return function(d){null===b?c?c.push(d):(c=[d],La(xa(a),a,function(a,d){b=d;for(var g=0,h=c.length;g!=h;g++)c[g](a,d);c=null})):d(w,b)}},hc=sb("uaparser"),ic=function(a){return function(b){var c=b[1]||"name";return{get:function(b){hc(function(f,
e){b(e&&e[a][c]||null)})}}}},jc=sb("blocksensing"),kc={eq:function(a,b,c){return b.join?0<=b[0].indexOf(a)&&(!b[1]||0>b[1].indexOf(a)):c?c(String(a))==c(String(b)):a==b},contains:function(a,b){return 0<=a.indexOf(b)},starts:function(a,b){return 0==a.indexOf(b)},ends:function(a,b){var c=a.lastIndexOf(b);return 0<=c&&c==a.length-b.length},matches:function(a,b){return null!==a.match(new ka(b))},"matches-ci":function(a,b){return null!==a.match(new ka(b,"i"))},lt:function(a,b,c){return c?c(String(a))<
c(String(b)):a<b},le:function(a,b,c){return c?c(String(a))<=c(String(b)):a<=b},gt:function(a,b,c){return c?c(String(a))>c(String(b)):a>b},ge:function(a,b,c){return c?c(String(a))>=c(String(b)):a>=b},"true":function(a){return a},"in":function(a,b,c){c&&(a=c(String(a)));for(var d=0,f=b.length;d<f;d++){var e=b[d];if(e.join){if(0<=e[0].indexOf(a)&&(!e[1]||0>e[1].indexOf(a)))return 1}else if((c?c(String(e)):e)==a)return 1}return 0}},lc={lt:1,le:1,gt:1,ge:1},sa,tb,ub=function(){var a=X.search;if(!sa||a!==
tb){tb=a;var b=/\+/g,c=/([^&=]+)=?([^&]*)/g,d=a.substring(1);for(sa={};a=c.exec(d);)sa[decodeURIComponent(a[1].replace(b," "))]=decodeURIComponent(a[2].replace(b," "))}},vb=function(a){var b={};if(a)for(var c=0,d=a.length;c!=d;c++)b[a[c]]=1;return{sel:b,ch:{}}},Da,wb,Sa,xb,mc=function(a,b){var c=T("","ps",a,b);if(!Da){var d=m.history;Da=d.pushState;d.pushState=wb=function(){Da.apply(this,arguments);z("","ps")};Sa=d.replaceState;d.replaceState=xb=function(){Sa.apply(this,arguments);z("","ps")}}return c},
Ta={URL:function(a,b){var c=a[1],d={};if(c&&"whole"!=c)switch(c){case "queryParam":d.get=function(a){ub();a(sa[b.name])};break;case "protocol":d.get=function(a){a(X.protocol.replace(/:$/,""))};break;default:d.get=function(a){a(X[c])}}else d.get=function(a){a(X.toString())};if(m.history){var f,e;d.listen=function(a,b){f=K(m,"popstate",b,a);e=mc(b,a)};d.stop=function(){Q(m,"popstate",f);if(0>U("","ps",e)){var a=m.history;--pushStateCntr||(a.pushState==wb&&(a.pushState=Da),a.replaceState==xb&&(a.replaceState=
Sa))}}}return d},UA:function(){return{get:function(a){a(S.userAgent)}}},Referrer:function(){return{get:function(a){a(n.referrer)}}},Event:function(a,b){var c,d=b.name;return{listen:function(a,b){ea[d]&&(b(),delete ea[d]);c=T("ev",d,b,a)},stop:function(){U("ev",d,c)}}},Language:function(a){var b={get:function(b){var c=S.language||S.userLanguage||S.browserLanguage;b("string"==typeof c?("base"==a[1]?c.split(/[_-]/)[0]:c).toLowerCase():w)}};if(aa){var c;b.listen=function(a,b){c=K(m,"languagechange",b,
a)};b.stop=function(){Q(m,"languagechange",c)}}return b},Location:function(){return{get:gc}},Const:function(a,b){return{get:function(a){a(b.value)}}},Var:function(a,b){return{get:function(a){for(var d=b.name.split("."),f=m,e=0,g=d.length;e<g&&f!==w;e++)f=f[d[e]];a(f)}}},Code:function(a,b,c){return{get:function(a){var f=function(){var c;try{c=eval(b.code)}catch(f){m.console&&console.log(f)}a(c)};c?Ba(f):f()}}},Data:function(a,b){var c,d=b.name;return{get:function(a){a(Oa[d])},listen:function(a,b){c=
T("var",d,b,a)},stop:function(){U("var",d,c)}}},DOMText:function(a,b){return{get:function(a){Ba(function(){var d=n.getElementById(b.id);a(d?d.innerHTML:w)})}}},DOMAttr:function(a,b){return{get:function(a){Ba(function(){var d=n.getElementById(b.id);a(d?d.getAttribute(b.attr):w)})}}},Rand:function(){return{get:function(a){a(String(Math.floor(4294967295*Math.random())))}}},Cookie:function(a,b){return{get:function(a){a(Ia(b.cookie))}}},Click:function(a,b){return Aa("click",b.sel)},FormSubmit:function(a,
b){return Aa("submit",b.sel)},InputChange:function(a,b){return Aa("change",b.sel)},DOMEvent:function(a,b){return Aa(b.ev,b.sel)},DOMLoaded:function(){var a;return{get:function(a){a(N)},listen:function(b,c){a=T("ev","mtm.dom",c,b)},stop:function(){U("ev","mtm.dom",a)}}},Timer:function(a,b){var c;return{listen:function(a,f){var e=function(){f(vb(a))};c=__mtm_tags._overriddenAPIs.setInterval(e,b.delay);b.first&&e()},stop:function(){m.clearInterval(c)}}},ScrollDepth:function(){var a;return{get:function(a){a(hb())},
listen:function(b,c){a=K(m,"scroll",c,b)},stop:function(){Q(m,"scroll",a)}}},AdBlocking:function(){return{get:function(a){jc(function(b,c){a(b||c?1:0)})}}},PageVisible:function(){if("string"==typeof n.visibilityState){var a;return{get:function(a){a("visible"==n.visibilityState?1:0)},listen:function(b,c){a=K(n,"visibilitychange",c,b)},stop:function(){Q(n,"visibilitychange",a)}}}return{get:function(a){a(1)}}},PageInFocus:function(){var a=n.hasFocus,b=a?n.hasFocus()+0:1,c,d;return{get:function(d){!c&&
a&&(b=n.hasFocus()+0);d(b)},listen:function(a,e){c=K(m,"focus",function(a){b=1;e(a)},a);d=K(m,"blur",function(a){b=0;e(a)},a)},stop:function(){Q(m,"focus",c);Q(m,"blur",d);c=0}}}},ta={"URL.port":0,"URL.protocol":2,"URL.hostname":2,Language:2,"Language.base":2,"Location.lon":1,"Location.lat":1,"Device.type":2,"Device.manufacturer":2,Rand:0,ScrollDepth:0},nc=["Browser","OS","Device"],oc=["major","minor","patch"],Ua=0;3!=Ua;Ua++){var ga=nc[Ua];Ta[ga]=ic(ga.toLowerCase());ta[ga]=2;ta[ga+".family"]=2;
ta[ga+".version"]=3;for(var Va=0;3!=Va;Va++)ta[ga+"."+oc[Va]]=0}var yb=[function(a){var b;try{b=parseInt(a,10)}catch(c){return}return isNaN(b)?w:b},function(a){var b;try{b=parseFloat(a)}catch(c){return}return isNaN(b)?w:b},function(a){return a.toLowerCase()},function(a){a=a.split(".");for(var b=0,c=a.length;b!=c;b++){var d=a[b],f=d.length;6>f&&(a[b]=(new B(7-f)).join("0")+d)}return a.join(".")}],qc=function(a,b,c){if("s"==a)return{get:function(a){pc(b,c,function(){a(!0)})}};var d,f=a+b;return{listen:function(a,
b){d=T("tag",f,b,a)},stop:function(){U("tag",f,d)}}},zb=function(a){if(a){var b=a.type.split(/\./),c=Ta[b[0]];if(c)return c(b,a.params,a.visual)}},Ab=function(a,b,c){if(a)if(a=a.get){var d=b&&b["default"];a(d!==w?function(a){c(a||d)}:c)}else c();else c()},rc=function(a,b){Ab(zb(a),a,b)},Bb=function(a,b,c,d,f){if(b&&b.length){var e=m.__mtm_tags,g={sel:{},ch:{}};kb(0,g,b,function(b,f,l){(f=a[f])?Zb(b,g,[function(a,b){b(Na(f.temporalConditions,qa[f.timezone||c]||pa),g)},function(a,b){f.probabilityCondition?
f.probabilityCondition.calls?b(!(Math.random()*f.probabilityCondition.calls>=f.probabilityCondition.times),g):d(f,function(a){b(a||0,g)}):b(1,g)},function(a,b){if(f.pageConditions){var c=e.variables,d=function(a,b,d){var f,l,e,q,p,h=b.comparator;(p=b.tag)?(q=qc(h.charAt(0),p,b.options),h=h.substring(1)):((e=b.variable)?(f=c[e],f.num&&(l=yb[1])):(l=ta[e=b.systemVariable],l!==w&&(l=yb[l]),f={type:e}),q=zb(f));var k,r,s,m,n=kc[h],C=lc[h],ha=b.value,A=b.negate,E="tr"==h,G="nt"==h,z=function(a,b){Ab(q,
f,function(c){if(E||G)c===w||c?(r=1,b&&b(),d(E,a)):d(w,a);else{var f=Y(c),e,g;f&&(g=c.length);if(k)if(f){if(Y(s)&&g==s.length){var q;for(e=0;e<g;e++)if(c[e]!==s[e]){q=1;break}if(!q){d(w,a);return}}}else if(c===s){d(w,a);return}s=c;var p=m;q=function(c){C&&p===m?d(w,a):(k=1,c&&(r=1,b&&b()),d(c,a))};if(f)for(e=0;e<g;e++){if(m=n(c[e],ha,l)){q(!A);return}}else if("string"==typeof c||"number"==typeof c||null==c){m=n(null==c?"":c,ha,l);q(A?!m:m);return}m=!1;q(A)}})};q.get?z(g):d(0,g);var D=b.once||G;if(q.listen&&
(!r||!D)){var y=q.stop;if(G){var F=function(){__mtm_tags._overriddenAPIs.setTimeout(function(){r||(r=1,y&&y(),d(1,vb(a)))},ha)};if(p){p="p"+p;var B=T("tag",p,function(){U("tag",p,B);F()})}else F()}q.listen(a,function(a,b){D&&r||b?d(w,a):z(a,function(){D&&y&&y()})})}},l=function(a,b,c){Y(b)?jb(a,g,b,l,c):b.or?kb(a,g,b.or,l,c):d(a,b,c)};l(a,f.pageConditions,b)}else b(1,g)}],l):l(0,g)},f)}else f(1)},ia,sc=function(){return{vis:{},data:{},push:function(a,b){this.data[a]=b;var c=this.update;c&&c(b)}}},
Cb=function(a,b){if(a&&a.length){var c=[],d=m.__mtm_tags,f=d.crules;ca(a,function(a,b){Bb(f,[a],d.timezone,function(a,b){b(!0)},function(d){d&&c.push(f[a]);b()})},function(){b(c)})}else b()},Db=function(a,b,c,d){c||(c={});var f,e,g=function(){if(f){var a=m.googletag;a&&(a=a.cmd)&&a.push==e&&(a.push=f)}};c.error=function(b){m.console&&console.log(b.msg?"ERROR from "+a+": "+b.msg:b);g();d&&d(b)};c.innerHTMLSetter=__mtm_tags._overriddenAPIs.innerHTMLSetter;c.beforeEnqueue=function(){var a=m.googletag;
a&&(a=a.cmd,Y(a)||(f=a.push,a.push=e=function(){var a=arguments,b=this;setTimeout(function(){f.apply(b,a)},0)}))};c.done=function(){g();b&&b.apply(this,arguments)};return c},Eb=function(a,b){var c=P[a].id;return Db("tag "+c,function(){P[a].oe=ma();z("tag","_l",c);z("tag","l"+c);b()},{mtmsid:a},function(b){var f=b.errorMsg;f&&(b=b.url,P[a].err={m:f,t:ma(),url:b==X.href?null:b});z("tag","_e",c)})};Ca.exec=function(a){"string"==typeof a&&(a={code:a});Xa(a.loc?"string"==typeof a.loc?n.getElementById(a.loc):
a.loc:n.getElementsByTagName("body")[0]||n.getElementsByTagName("head")[0],a.code,Db("user code",a.callback))};var Fa=function(a,b){if(a instanceof Element)return[[a]];if(Y(a))return a[0]?[a]:[];var c=a.split(/::/),d=c[0],f;try{f=Ja(d,b)}catch(e){return[]}return f.length?[f,d,c[1]]:[]},Fb=function(a,b,c,d,f,e){var g=!1,h=b.place;if(h&&"string"==typeof b.code){var k=b.selector;!k&&(k=Fa(h.sel,h.multi),k.length||e===w)&&(b.selector=k);if(!k.length)g=e||!1;else if(!(g=f[c])){e=k[0];g=-1;h=0;for(k=e.length;h!=
k;h++){var l=e[h].getBoundingClientRect(),l=Math.abs((l.top+l.bottom>>1)-a);if(0>g||l<g)g=l}f[c]=g}!1!==g&&(d[b.id]=g)}if(b=I["-"+c])for(var r in b)Fb(a,da[r][0],r,d,f,g)},Gb=function(a,b,c,d){if(b.metric)return b.metric;var f={};Fb(a,b,c,f,d);a=0;for(var e in f)a+=f[e]?1/f[e]:1;return b.metric=a},tc={before:"mzbt-pos-before",after:"mzbt-pos-after","-mzbt-prepend":"mzbt-pos-prepend"},Hb=function(a,b,c,d,f){for(;b;){var e=b[c];if(b.className==d){if(f)return 1;a.removeChild(b)}b=e}},uc=function(a,b,
c){var d=n.createElement("span"),f=tc[a]||"mzbt-pos-append";d.className=f;var e=b.parentNode,g,h=2==c;switch(a){case "before":if(c&&Hb(e,b.previousSibling,"previousSibling",f,h))break;return e.insertBefore(d,b);case "after":if((g=b.nextSibling)&&c&&Hb(e,g,"nextSibling",f,h))break;return(g=b.nextSibling)?e.insertBefore(d,g):e.appendChild(d);default:e=b.childNodes;g=e.length;if(c)for(c=0;c!=g;)if(e[c].className==f){if(h)return;b.removeChild(e[c]);g--}else c++;return"-mzbt-prepend"==a&&g?b.insertBefore(d,
e[0]):b.appendChild(d)}},Ib={},Ga={},pc=function(a,b,c){if(Ib[a])c();else if(Ga[a])Ga[a].push(c);else{var d=[c];Ga[a]=d;Ba(function(){F.when(a,function(c){var e=c.place;if(e){var g=c.selector,h=e.multi;g||(g=Fa(e.sel,h),g.length&&(c.selector=g));if(g.length){var k=g[0];if(k){var l=b&&b.depth||0,r,p,u;c=function(){for(var b=(m.innerWidth||n.documentElement.clientWidth)+l,c=(m.innerHeight||n.documentElement.clientHeight)+l,f=0,e=k.length;f!=e;f++){var g=k[f];if(g.getClientRects().length&&(g=g.getBoundingClientRect(),
g.top<c&&g.bottom>=-l&&g.left<b&&g.right>=-l)){u=Ib[a]=!0;r&&rb(r);p&&clearInterval(p);delete Ga[a];b=0;for(c=d.length;b!=c;b++)d[b]();break}}};c();u||(r=Ra(c),(e=b&&b.poll)&&(p=__mtm_tags._overriddenAPIs.setInterval(c,e)))}}}})})}},Ya={},Ha={},ja=function(a,b,c){var d=F[b];if(d)for(var f in a){var e=a[f];f=f.split(".");for(var g=d,h=0,k=f.length;g&&h!=k;h++)g=g[f[h]];g&&e(b,g,c)}};(function(){var a="width top bottom position display z-index left right".split(" "),b={IMG:!0,VIDEO:!0,AUDIO:!0,EMBED:!0,
OBJECT:!0,IFRAME:!0},c=function(a,d){switch(a.nodeType){case 3:return d||""==a.nodeValue.replace(/[\s\n\r]/g,"");case 1:if(!a.getClientRects().length)break;var f=m.getComputedStyle(a);if("hidden"==f.visibility||!f.opacity)break;if(b[a.tagName.toUpperCase()])return;for(var f=a.childNodes,e=0,r=f.length;e!=r;e++)if(!c(f[e]))return}return!0},d,f,e=function(){f||(f=!0,Tb(function(){f=!1;var b=function(f,e){var l=f[0],r=f[1],p=l.style,u=l.__mtm_oldInfo,s=function(){if(!u){var b=n.createElement("div");
b.className="mtm-sticky-placeholder";var c=b.style;c.visibility="hidden";c.display="block";u={};a.forEach(function(a){u[a]=p[a]});var d=m.getComputedStyle(l),f=d.display;"block"!=f&&"none"!=f&&(p.display=u.display="block");"auto"!=d.left&&(u.absLeft=1,u.absLeftMargin=parseInt(d["margin-left"],10)||0);["box-sizing","width","height"].forEach(function(a){c[a]=d[a]||"0"});["left","right","top","bottom"].forEach(function(a){["margin","padding"].forEach(function(b){b=b+"-"+a;c[b]=d[b]||"0"});var b="border-"+
a+"-width";c[b]=d[b]||"0";c[a]=d[a]||"auto"});c.position=d.position;u.placeholder=b;l.__mtm_oldInfo=u;f=l.clientWidth;if(!f&&"visible"==d.overflow)for(var e=l.children,q=0,g=e.length;q!=g;q++){var h=e[q].clientWidth;h>f&&(f=h)}p.width=f+"px";p.display="block";"static"==d.position&&(p.position="relative");"auto"==d["z-index"]&&(p["z-index"]=1);l.parentNode.insertBefore(b,l)}},q=l.getBoundingClientRect(),x=r.bottom,t=x?"bottom":"top",Z=x?"top":"bottom",v=parseInt(m.getComputedStyle(l)["margin-"+t])||
0;r.bottom||(v=-v);var M=q[t],v=M+v,O=l.__mtm_stickyState||0,Ea,w;O&&(w=u.placeholder.getBoundingClientRect());var y=function(){u.absLeft&&(p.left=q.left-u.absLeftMargin+"px",p.right="auto");p.position="fixed"},z=function(){var a=q.bottom,f=q.left,h=q.right,x=function(b){if(b.offsetWidth||b.offsetHeight){var c=b.getBoundingClientRect(),d=c.top,e=parseInt(m.getComputedStyle(b)["margin-top"])||0;0<e&&(d-=e);e=c.left;if(f<c.right&&e<h)return d>=w.bottom&&d<a&&(Ea=b,a=d),!0}};if(r.brk)for(var v=Ja(r.brk,
!0),t=0,M=v.length;t!=M;t++)x(v[t]);r.brkSticky&&d.forEach(function(a){a=a[0];a==l||a.__mtm_stickyState||x(a)});if(!(r.brk||r.brkSticky||r.nobrk))for(var v=l,n,t=function(a){a=a[0];return n==a||a.__mtm_oldInfo&&n==a.__mtm_oldInfo.placeholder};v&&v instanceof Element;){for(n=v;(n=n.nextSibling)&&c(n,!0););if(n&&(2==n.__mtm_stickyState||!d.some(t))&&x(n))break;v=v.parentNode}if(Ea){s();if("fixed"==m.getComputedStyle(Ea).position)y(),p.top="auto",p.bottom=a+"px";else if(p.position="absolute",p.left=
u.left,p.right=u.right,v=l.offsetParent)"static"==m.getComputedStyle(v).position&&(v.style.position="relative"),p.top="auto",p.bottom=v.getBoundingClientRect().bottom-a+"px";l.__mtm_stickyState=2;e&&(v=e-1,b(d[v],v))}};1==O&&z();if(!Ea){var ua=function(){l.parentNode.removeChild(u.placeholder);a.forEach(function(a){p[a]=u[a]});delete l.__mtm_oldInfo;delete l.__mtm_stickyState;delete l.__mtm_topPinned},V=m.innerHeight,L=l.__mtm_topPinned,J=x?m.innerHeight:0,C,ha=function(a){x?(p.bottom=V-J+"px",p.top=
"auto"):(p.top=J+"px",p.bottom="auto");C&&!a&&(L?0>L.indexOf(C)&&L.push(C):l.__mtm_topPinned=[C]);q=l.getBoundingClientRect();u=l.__mtm_oldInfo;w||(w=u.placeholder.getBoundingClientRect());z()};if(1==O){var A;if(w.top>q.top)ua();else if(L&&(A=L.length)){for(var E=0;E!=A;E++){var t=L[E],G=t.getBoundingClientRect()[Z];if(x?G<J:G>J)J=G,C=t}M!=J&&ha(1)}}else{if(!r.ignoreTopSticky&&(E=l.__mtm_oldScrollPos,"undefined"==typeof E&&(E=v+hb()),0<=E||0<=v)){M=p.visibility;p.visibility="hidden";var F=q.left+
q.right>>1,D;E>v?(D=E,A=v):(D=v,A=E);var B=r.bottom?A:D;0>A&&(A=0);D>V&&(D=V);var H,I=function(){for(var a=n.elementFromPoint(F,D);a&&a instanceof Element;){var b=L&&0<=L.indexOf(a);if(b)H=1;else{var c=m.getComputedStyle(a);if("fixed"==c.position)if(b=c.top,r.bottom&&"auto"==b&&"auto"!=c.bottom||!r.bottom&&"auto"!=b)b=1;else break}if(b)return C=a,J=a.getBoundingClientRect()[Z],!0;a=a.parentNode}},E=0,K=d.length;if(r.bottom){G=D;D=A;for(A=G;E!=K;E++){var R=d[E][0];if(R!=l&&1==R.__mtm_stickyState&&
(G=R.getBoundingClientRect()[Z],G>=B&&G<=A&&(C=R,A=(J=G)-1,B>=A)))break}if(!C||D<A)for(;D<=A&&!I();D+=10);}else{for(;E!=K&&!(R=d[E][0],R!=l&&1==R.__mtm_stickyState&&(G=R.getBoundingClientRect()[Z],G<=B&&G>=A&&(C=R,A=(J=G)+1,B<=A)));E++);if(!C||D>A)for(;D>=A&&!I();D-=10);}C||D==A||I();p.visibility=M}if(2==O&&w[t]>=J&&w.top<=q.top)ua();else if(2==O&&v>J||0==O&&v<=J)s(),y(),l.__mtm_stickyState=1,ha(H)}}l.__mtm_oldScrollPos=v};d.forEach(b)}))};Ha["place.sticky"]=function(a,b){var c=ia.vis[a];c&&n.addEventListener&&
(c.forEach(function(a){var b=m.getComputedStyle(a),c=b.display;a=a.style;"block"!=c&&"none"!=c&&(a.display="block");"none"!=b["float"]&&(a["float"]="none");"both"!=b.clear&&(a.clear="both")}),c=c.map(function(a){return[a,b]}),d?d=d.concat(c):(d=c,Ra(e)),d.sort(function(a,b){return a[0].getBoundingClientRect().top-b[0].getBoundingClientRect().top}),e())};Ca["tag.sticky"]=function(b){b&&(b=b.update,"function"==typeof b&&(d?(d.forEach(function(b){if(b.__mtm_stickyState){var c=b.__mtm_oldInfo;b.parentNode.removeChild(c.placeholder);
var d=b.style;a.forEach(function(a){d[a]=c[a]});delete b.__mtm_oldInfo;delete b.__mtm_stickyState;delete b.__mtm_topPinned}delete b.__mtm_oldScrollPos}),b(),e()):b()))}})();var vc=function(a,b,c){var d="mzbtn-"+a;if(!Ia(d)){var f,e,g,h=n.createElement("div"),k=n.createElement("div"),l,r,p,u=function(){n.cookie=d+"=1;path=/;expires="+(new y((new y).getTime()+31536E6)).toUTCString();h.parentNode.removeChild(h);p&&p.parentNode.removeChild(p);r&&Q(m,"resize",r)};h.className="mzbt-notice-wrapper";a=n.createElement("div");
a.className="mzbt-notice-container";__mtm_tags._overriddenAPIs.innerHTMLSetter(a,(b.styles?"<style scoped='1'>"+b.styles+"</style>":"")+b.data);k.appendChild(a);h.appendChild(k);a=3==b.ypos.from;var s="position:"+(a?"relative":"fixed")+";width:"+b.width;b.modal||(s+=";z-index:2147483647");var q="width:100%;padding:0;overflow-y:auto",x=b.height,t=x.length-1;"%"==b.height.charAt(t)?g=parseFloat(b.height.substring(0,t)):q+=";max-height:"+x;switch(b.xpos.from){case 2:s+=";right:"+b.xpos.offs;break;case 1:a?
s+=";margin-left:auto;margin-right:auto":(s+=";left:50%",f=1);q+=";margin-left:"+b.xpos.offs;break;default:s+=";left:"+b.xpos.offs}switch(b.ypos.from){case 2:s+=";bottom:"+b.ypos.offs;q+=";position:absolute;bottom:0";break;case 1:s+=";top:50%";q+=";margin-top:"+b.ypos.offs;e=1;break;default:s+=";top:"+b.ypos.offs}if(f||e||g)s+=";visibility:hidden",l=function(){f&&(h.style.marginLeft=-(h.offsetWidth/2)+"px");e&&(h.style.marginTop=-(h.offsetHeight/2)+"px");g&&(k.style.maxHeight=((m.innerHeight||(n.documentElement&&
n.documentElement.offsetHeight?n.documentElement.offsetHeight:n.body.offsetHeight))*g/100|0)+"px")},r=K(m,"resize",l);h.setAttribute("style",s);k.setAttribute("style",q);s=function(a){for(var b=0;b<a.length;b++)K(a[b],"click",u);for(b=0;b<a.length;b++){var c=a[b];"a"!=c.tagName.toLowerCase()||c.getAttribute("href")||c.setAttribute("href","javascript:void(0)")}};if(b.autoDismiss)if(2==b.autoDismiss)s([h]);else{s(h.getElementsByTagName("a"));s(h.getElementsByTagName("button"));q=h.getElementsByTagName("input");
x=[];for(t=0;t<q.length;t++){var Z=q[t].getAttribute("type");Z&&"button"==Z.toLowerCase()&&x.push(q[t])}s(x)}else s(Rb(h,"mzbt-popup-dismiss"));a?(b=c.firstChild)?c.insertBefore(h,b):c.appendChild(h):b.modal?(p=n.createElement("div"),p.className="mzbt-notice-overlay",p.setAttribute("style","position:fixed;overflow:auto;top:0;left:0;bottom:0;right:0;z-index:2147483647"),p.appendChild(h),c.appendChild(p)):c.appendChild(h);l&&(l(),h.style.visibility="visible")}},Jb=function(a,b){var c=a.id,d;for(d in F){var f=
F[d],e=f.depends;e&&0<=e.indexOf(c)&&!b[d]&&Za(f,!0,function(a,c){a.lazy&&c?b[d]=f:Jb(f,b)})}},$a=0,wc=function(a,b,c){Za(b,!0,function(d,f){var e=d.lazy;if(e){var g=[],h=e.pageStatus;h&&g.push({systemVariable:h,comparator:"true",once:1});var h=e.selector,k;if(h){var l="lazy-"+$a++,h={id:l,fake:1,tagCode:{type:"VIRT"},place:{sel:h}};a.push(h);F.add(l,h);g.push({comparator:"str",tag:l});k=[g]}else{if(f)h=[b],l={depth:e.scroll,poll:e.poll};else{e={};Jb(b,e);h=[];for(k in e)h.push(e[k]);if(!h.length)return}e=
h.length;k=new B(e);for(var r=0;r!=e;r++){var p=g.slice();p.push({comparator:"str",tag:h[r].id,options:l});k[r]=p}}g=k;l=g.length;if((h=b.activationRules)&&h.length)for(e=h.length,k=[],q=0;q!=l;q++)for(r=g[q],p=0;p!=e;p++){var u=JSON.parse(JSON.stringify(c[h[p]])),s=u.pageConditions;u.pageConditions=s?r.concat(s.concat?s:[s]):r;s="lazy-"+$a++;c[s]=u;k.push(s)}else{k=new B(l);for(var q=0;q!=l;q++)s="lazy-"+$a++,c[s]={pageConditions:g[q]},k[q]=s}b.activationRules=k}})},va={},F={when:function(a,b){F[a]?
b(F[a]):(va[a]||(va[a]=[]),va[a].push(b))},add:function(a,b){F[a]=b;var c=va[a];if(c){delete va[a];for(var d=0,f=c.length;d!=f;d++)c[d](b)}}},ab=[],xc=function(a){for(var b=0,c=ab.length;b!=c;b++)a=ab[b](a);return a},yc=function(a,b){var c=I["-"+a];if(c)for(var d in c)if(b(da[d][0],d))break},zc=1,bb={},Za=function(a,b,c){var d=a.id,f=bb[d];if(f)b||delete bb[d],c.apply(this,f);else{var f=a.tagCode,e=a.place,g=Y(f),h=Y(e),k=null,l={};if(g||h){var r=100*Math.random(),p=0,u=g?f:a.place,s=u.length,q,x=
a.persistABInSession,t;if(x&&(k=Ia(t="mzbtp-"+a.id),"string"==typeof k&&k.length))try{k=parseInt(k,10),0<=k&&k<s&&(q=1)}catch(m){}if(!q)for(k=s-1,a=0;a!=s;a++)if(r<(p+=u[a][0])){k=a;x&&(n.cookie=t+"="+a+";path=/");break}g&&(f=f[k][1]);h&&(e=e[k],g||(e=e[1]));l.varn=k}b&&(bb[d]=[f,e,l]);c(f,e,l)}},Ac=/\{\{-?([^\{\}]+)\}\}/g,Bc=/^VisualPlacement(?:\.(?:id|pos))?$/,Cc=function(a,b,c,d){for(var f=[],e={},g,h;null!==(g=Ac.exec(a));)h=g[1],Bc.test(h)||(e[h]=!0);for(h in e)f.push(h);var k=m.__mtm_tags.variables;
ca(f,function(a,b){rc((k?k[a]:null)||{type:a},function(c){e[a]=c;b()})},function(){f.length&&(a=a.replace(/\{\{\{\{|\{\{(-?)([^\{\}]+)\}\}/g,function(d,f,g,h){return g?(g=e[g],g!==w?(g=null===g?"":String(g),f||b?h=g:c?(d=g,h=a.substring(0,h),h=Qb.test(h.replace(Pb,""))?na(d):eb(d)):h=na(g),h):d):"{{"}));d(a)})},Kb=function(a,b){Za(a,!1,function(c,d,f){var e=function(a){b(a,d,f)};if("function"==typeof c)e(c);else{var g=c.type,h=c.data;switch(g){case "CODE":e(h);return;case "VIRT":e();return}var k=
c.type;Cc(h,"HTML URL"==k||"JS URL"==k,"HTML"==k,function(b){switch(g){case "HTML":e(b);break;case "JS":e("<script>"+b.replace(/<\/(script)\b/gi,"<\\/$1")+"\x3c/script>");break;case "HTML URL":e("<script>__mtm_load('"+na(b)+"',true)\x3c/script>");break;case "JS URL":e("<script src='"+eb(b)+"'>\x3c/script>");break;case "POPUP":e(function(b,d){vc(a.id,c,b);d()});break;default:e("")}})}})},Lb=function(a){z("tag","_l",a);z("tag","l"+a);z("tag","f"+a)},Dc=0,Ec=function(){var a=S.userAgent.match(/\bMSIE\s+([\d\.]+)/);
a&&(a=10>parseFloat(a[1]));return a}(),fa=function(a){return function(){var b=n.body,c=b;if((a=xc(a)).length){if(b){if(N&&1<a.length&&b.getBoundingClientRect){var d=(m.innerHeight||n.documentElement.clientHeight)/3,f={};a.sort(function(a,b){return Gb(d,b[0],b[1],f)-Gb(d,a[0],a[1],f)})}}else c=(c=n.getElementsByTagName("script")[0])?c.parentNode:n.getElementsByTagName("head")[0];var e=[],g=[],h=function(a,b){e.push([a,1]);g.push(b)},k=[];ca(a,function(a,d){var f=a[0],e=a[1],g=function(){var a=zc++;
P[a]={id:e,state:f.state,os:ma(),fake:F[e].fake};z("tag","p"+e);return a},q,x,t,m,v=f.place;v&&(q=v.sel,x=v.multi,t=v.subseq);var M=f.code,O="function"==typeof M;if(q||O)if(N)if(O&&!q)k.push(e),m=g(),M(b,function(){P[m].oe=ma();Lb(e);ja(Ya,e,f);d()}),ja(Ha,e,f);else if(q=f.selector||Fa(q,x),x=q[0]){var w=q[2],y=w?w.replace(/^-mzbt-/,""):"after",B=q[1],Wa=ia.vis[e]=[],ua="string"==typeof f.code,V;ca(x,function(a,c){if(ua){var d,f,e=M.replace(/\{\{\{\{|\{\{(-?)(VisualPlacement(?:\.(id|pos))?)\}\}/g,
function(b,c,e,q){if(!e)return"{{";if("pos"==q)return y;if(q)return f||(f=a.getAttribute("id"))||a.setAttribute("id",f="mzbtEl"+Dc++),d=1,c?f:na(f);d=1;return c?B:na(B)});if(d){containerEl=b;if(t&&a.getAttribute("mtmex")){if(2==t){c();return}for(var q=a.childNodes,l=q.length-1;0<=l;l--)a.removeChild(q[l])}a.setAttribute("mtmex","1");V=1;Wa.push(a)}else if(containerEl=uc(w,a,t))V=1,Wa.push(containerEl);else{c();return}ba.postscribe(containerEl,e,Eb(g(),c))}else V=1,Wa.push(a),m=g(),e=function(){P[m].oe=
ma();c()},O?M(a,e):e()},function(){V&&k.push(e);ua||Lb(e);ja(Ya,e,f);d()});ja(Ha,e,f)}else z("tag","d"+e),d();else h(f,e),d();else if(q=function(){k.push(e);ba.postscribe(c,f.code,Eb(g(),function(){ja(Ya,e,f);d()}));ja(Ha,e,f)},N)q();else if(Ec)h(f,e),d();else if(ba.mode)q();else{v=n.createElement("div");__mtm_tags._overriddenAPIs.innerHTMLSetter(v,f.code);x=!1;for(var v=v.children,L=0,J=v.length;L!=J;L++){var C=v[L].nodeType;if(3==C){x=!0;break}if(1==C&&(C=v[L].nodeName.toLowerCase(),"script"!=C&&
"noscript"!=C&&"link"!=C&&"meta"!=C)){x=!0;break}}x?(h(f,e),d()):q()}},function(){for(var a=[],b,c=k.length,d=0;d!=c;d++)F[b=k[d]].fake||a.push(b);a.length&&((new Image).src="//stats.mezzobit.com/tag-log?c="+__mtm[0]+"&ids="+a.join(",")+"&r="+Ob);if(c=e.length){I["mtm.dom"]||(I["mtm.dom"]={});for(d=0;d!=c;d++)I["mtm.dom"][b=g[d]]=1,da[b]=e[d];N&&ea["mtm.dom"]&&ya("mtm.dom")}})}}},Mb=function(a,b){var c=m.__mtm_tags,d=c.rules;wc(c.tags,a,d);Bb(d,a.activationRules,a.timezone||c.timezone,function(b,
c){La("//tdi.mezzobit.com/rate-limit/i"+a.id+"_"+b.id,"rateLimit"+a.id,function(a,b){c(b)})},function(a){a&&b()})},Fc=0;Ca.tag=function(a){var b=a.id="i"+Fc++;a.fake=1;F.add(b,a);Mb(a,function(){Kb(a,function(b,d,f){b={code:b,place:d,state:f};b=fa([[b,a.id]]);a.activationDelay?data._overriddenAPIs.setTimeout(b,a.activationDelay):b()})})};var Gc=function(a){var b=function(){a(m.googletag)},c=m.googletag;c&&"function"==typeof c.enableServices?b():(c||(m.googletag=c={}),c.cmd||(c.cmd=[]),c.cmd.push(b))},
Hc=function(a){if(a=a.gtr){var b=Ta[a]();if(b.listen){var c=function(a,b){var c=a[1],g=b[1];if(c&&g)try{if(c!=g&&JSON.stringify(c)!=JSON.stringify(g))return}catch(h){return}else if(c||g)return;c=a[0];g=b[0];if(c&&g){var k=c.length;if(k!=g.length)return;for(var l=0;l!=k;l++)if(c[l]!=g[l])return}else if(c||g)return;return 1};Gc(function(a){a=a.pubads();var f=a.refresh,e=[];a.refresh=function(){var a=this,d=arguments;b.get(function(k){if(k)setTimeout(function(){f.apply(a,d)},0);else{k=e.length;if(3>
d.length)for(var l=0;l!=k;l++)if(c(d,e[l]))return;e.push(d);k||b.listen(0,function(){b.get(function(c){if(c){b.stop();c=0;for(var d=e.length;c!=d;c++)(function(b){setTimeout(function(){f.apply(a,b)},0)})(e[c]);e=[]}})})}})}})}}},Xa=function(){(function(){function a(a,h){a=a||"";h=h||{};var p=h.innerHTMLSetter,k;for(k in b)b.hasOwnProperty(k)&&(h.autoFix&&(h["fix_"+k]=!0),h.fix=h.fix||h["fix_"+k]);var s=n.createElement("div"),q=function(b){a=b+a},x={comment:/^\x3c!--/,endTag:/^<\//,atomicTag:/^<\s*(script|style|noscript|iframe|textarea)[\s\/>]/i,
doctypeTag:/^<\!doctype[^>]*>/i,startTag:/^</,chars:/^[^<]/},t={comment:function(){var b=a.indexOf("--\x3e");if(0<=b)return{content:a.substr(4,b-1),length:b+3}},endTag:function(){var b=a.match(f);if(b)return{tagName:b[1],length:b[0].length}},atomicTag:function(){var b=t.startTag();if(b){if(b.unary)return delete b.unary,b.content="",b;var c=a.slice(b.length);if(c.match(new ka("</\\s*"+b.tagName+"\\s*>","i"))&&(c=c.match(new ka("([\\s\\S]*?)</\\s*"+b.tagName+"\\s*>","i"))))return{tagName:b.tagName,
attrs:b.attrs,content:c[1],length:c[0].length+b.length}}},doctypeTag:function(){var b=a.indexOf(">");return 0>b?null:{length:b+1}},startTag:function(){if(0>a.indexOf(">"))return null;var b=a.match(d);if(b){var f=b[2],q=f.length,h=0;do{var k="'",x=f.indexOf('"',h),m=f.indexOf("'",h),t=0>m;if(0<=x&&(t||m>x))m=x,k='"';else if(t)break;h=f.indexOf(k,m+1);if(0>h)break;h++}while(h<q);if(!(0>h)||(b=a.match(c))){var u={};f.replace(e,function(a,b,c,d,f){a=c||d||f||g.test(b)&&b||null;b=b.toLowerCase();"string"===
typeof a&&-1!==a.indexOf("&")&&(p(s,a),a=s.textContent||s.innerText||a);u[b]=a});return{tagName:b[1],attrs:u,unary:!!b[3],length:b[0].length}}}},chars:function(){var b=a.indexOf("<");return{length:0<=b?b:a.length}}},m=function(){for(var b in x)if(x[b].test(a)){var c=t[b]();return c?(c.type=c.type||b,b=c.length,c.text=a.substr(0,b),a=a.slice(b),c):null}};h.fix&&function(){var b=/^(AREA|BASE|BASEFONT|BR|COL|FRAME|HR|IMG|INPUT|ISINDEX|LINK|META|PARAM|EMBED)$/i,c=/^(COLGROUP|DD|DT|LI|OPTIONS|P|TD|TFOOT|TH|THEAD|TR)$/i,
d=[];d.last=function(){return this[this.length-1]};d.lastTagNameEq=function(a){var b=this.last();return b&&b.tagName&&b.tagName.toUpperCase()===a.toUpperCase()};d.containsTagName=function(a){for(var b=0,c;c=this[b];b++)if(c.tagName===a)return!0;return!1};var f=function(a){a&&"startTag"===a.type&&(a.unary=b.test(a.tagName)||a.unary);return a},e=m,g=function(){var a=d.pop();q("</"+a.tagName+">")},p={startTag:function(a){var b=a.tagName;"TR"===b.toUpperCase()&&d.lastTagNameEq("TABLE")?(q("<TBODY>"),
k()):h.fix_selfClose&&c.test(b)&&d.containsTagName(b)?d.lastTagNameEq(b)?g():(q("</"+a.tagName+">"),k()):a.unary||d.push(a)},endTag:function(a){d.last()?h.fix_tagSoup&&!d.lastTagNameEq(a.tagName)?g():d.pop():h.fix_tagSoup&&(e(),k())}},k=function(){var b=a,c=f(e());a=b;if(c&&p[c.type])p[c.type](c)};m=function(){k();return f(e())}}();return{append:function(b){a+=b},prepend:q,readToken:m,readTokens:function(a){for(var b;(b=m())&&(!a[b.type]||!1!==a[b.type](b)););},clear:function(){var b=a;a="";return b},
rest:function(){return a},stack:[]}}var b=function(){var a={},b=n.createElement("div");b.innerHTML="<P><I></P></I>";a.tagSoup="<P><I></P></I>"!==b.innerHTML;b.innerHTML="<P><i><P></P></i></P>";a.selfClose=2===b.childNodes.length;return a}(),c=/^<([\-A-Za-z0-9_]+)((?:\s+[\w\-]+(?:\s*=?\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,d=/^<([\-A-Za-z0-9_]+)([^>]*?)\s*(\/?)>/,f=/^<\/([\-A-Za-z0-9_]+)[^>]*>/,e=/([\-A-Za-z0-9_]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,
g=/^(checked|compact|declare|defer|disabled|ismap|multiple|nohref|noresize|noshade|nowrap|readonly|selected)$/i;a.supports=b;var h=function(a){return a.text};a.tokenToString=function(a){var b={comment:function(a){return"\x3c!--"+a.content},endTag:function(a){return"</"+a.tagName+">"},atomicTag:function(a){return b.startTag(a)+a.content+b.endTag(a)},doctypeTag:h,startTag:function(a){var b="<"+a.tagName,c;for(c in a.attrs)var d=a.attrs[c],b=b+(" "+c+'="'+(d?d.replace(/(^|[^\\])"/g,'$1\\"'):"")+'"');
return b+(a.unary?"/>":">")},chars:h};return b[a.type](a)};a.escapeAttributes=function(a){var b={},c;for(c in a){var d=a[c];b[c]=d&&d.replace(/(^|[^\\])"/g,'$1\\"')}return b};for(var k in b)a.browserHasFlaw=a.browserHasFlaw||!b[k]&&k;this.htmlParser=a}).call(this);(function(){function a(){}function b(a){return a!==w&&null!==a}function c(a,b,c){var d,f=a&&a.length||0;for(d=0;d<f;d++)b.call(c,a[d],d)}function d(a,b,c){for(var d in a)a.hasOwnProperty(d)&&b.call(c,d,a[d])}function f(a,b){d(b,function(b,
c){a[b]=c});return a}function e(a,c){a=a||{};d(c,function(c,d){b(a[c])||(a[c]=d)});return a}function g(a){try{return l.call(a)}catch(b){var d=[];c(a,function(a){d.push(a)});return d}}var h={afterAsync:a,afterDequeue:a,afterStreamStart:a,afterWrite:a,beforeEnqueue:a,beforeWrite:function(a){return a},done:a,error:function(a){throw a;},releaseAsync:!1},k=this,l=B.prototype.slice,m=function(){function a(c,d,f){var e=h+d;if(2===arguments.length)return e=c.getAttribute(e),b(e)?String(e):e;b(f)&&""!==f?
c.setAttribute(e,f):c.removeAttribute(e)}function e(b,c){var d=b.ownerDocument,g=__mtm_tags._overriddenAPIs;f(this,{root:b,options:c,win:d.defaultView||d.parentWindow,doc:d,onloadSetter:g.onloadSetter,onerrorSetter:g.onerrorSetter,parser:k.htmlParser("",{autoFix:!0,innerHTMLSetter:c.innerHTMLSetter}),actuals:[b],proxyHistory:"",proxyRoot:d.createElement(b.nodeName),scriptStack:[],writeQueue:[]});a(this.proxyRoot,"proxyof",0)}var h="data-ps-";e.prototype.write=function(){[].push.apply(this.writeQueue,
arguments);for(var a;!this.deferredRemote&&this.writeQueue.length;)a=this.writeQueue.shift(),"function"===typeof a?this.callFunction(a):this.writeImpl(a)};e.prototype.callFunction=function(a){var b={type:"function",value:a.name||a.toString()};this.onScriptStart(b);a.call(this.win,this.doc);this.onScriptDone(b)};e.prototype.writeImpl=function(a){this.parser.append(a);var b;a=[];for(var c,d;(b=this.parser.readToken())&&!(c=b&&"tagName"in b?!!~b.tagName.toLowerCase().indexOf("script"):!1)&&!(d=b&&"tagName"in
b?!!~b.tagName.toLowerCase().indexOf("style"):!1);)a.push(b);this.writeStaticTokens(a);c&&this.handleScriptToken(b);d&&this.handleStyleToken(b)};e.prototype.writeStaticTokens=function(a){a=this.buildChunk(a);if(a.actual)return a.html=this.proxyHistory+a.actual,this.proxyHistory+=a.proxy,this.options.innerHTMLSetter(this.proxyRoot,a.html),this.walkChunk(),a};e.prototype.buildChunk=function(a){var b=this.actuals.length,d=[],e=[],f=[];c(a,function(a){d.push(a.text);if(a.attrs){if(!/^noscript$/i.test(a.tagName)){var c=
b++;e.push(a.text.replace(/(\/?>)/," "+h+"id="+c+" $1"));"ps-script"!==a.attrs.id&&"ps-style"!==a.attrs.id&&f.push("atomicTag"===a.type?"":"<"+a.tagName+" "+h+"proxyof="+c+(a.unary?" />":">"))}}else e.push(a.text),f.push("endTag"===a.type?a.text:"")});return{tokens:a,raw:d.join(""),actual:e.join(""),proxy:f.join("")}};e.prototype.walkChunk=function(){for(var c,d=[this.proxyRoot];b(c=d.shift());){var e=1===c.nodeType;e&&a(c,"proxyof")||(e&&(this.actuals[a(c,"id")]=c,a(c,"id",null)),(e=c.parentNode&&
a(c.parentNode,"proxyof"))&&this.actuals[e].appendChild(c));d.unshift.apply(d,g(c.childNodes))}};e.prototype.handleScriptToken=function(a){var b=this.parser.clear();b&&this.writeQueue.unshift(b);a.src=a.attrs.src||a.attrs.SRC;if(a.src&&this.scriptStack.length)this.deferredRemote=a;else this.onScriptStart(a);var c=this;this.writeScriptToken(a,function(){c.onScriptDone(a)})};e.prototype.handleStyleToken=function(a){var b=this.parser.clear();b&&this.writeQueue.unshift(b);a.type=a.attrs.type||a.attrs.TYPE||
"text/css";this.writeStyleToken(a);b&&this.write()};e.prototype.writeStyleToken=function(a){var b=this.buildStyle(a);this.insertStyle(b);a.content&&(b.styleSheet&&!b.sheet?b.styleSheet.cssText=a.content:b.appendChild(this.doc.createTextNode(a.content)))};e.prototype.buildStyle=function(a){var b=this.doc.createElement(a.tagName);b.setAttribute("type",a.type);d(a.attrs,function(a,c){b.setAttribute(a,c)});return b};e.prototype.insertStyle=function(a){this.writeImpl('<span id="ps-style"/>');var b=this.doc.getElementById("ps-style");
b.parentNode.replaceChild(a,b)};e.prototype.onScriptStart=function(a){a.outerWrites=this.writeQueue;this.writeQueue=[];this.scriptStack.unshift(a)};e.prototype.onScriptDone=function(a){a!==this.scriptStack[0]?this.options.error({message:"Bad script nesting or script finished twice"}):(this.scriptStack.shift(),this.write.apply(this,a.outerWrites),!this.scriptStack.length&&this.deferredRemote&&(this.onScriptStart(this.deferredRemote),this.deferredRemote=null))};e.prototype.writeScriptToken=function(a,
b){var c=this.buildScript(a),d=this.shouldRelease(c),e=this.options.afterAsync;a.src&&(c.src=a.src,this.scriptLoadHandler(c,d?e:function(){b();e()}));try{this.insertScript(c),a.src&&!d||b()}catch(f){this.options.error(f),b()}};e.prototype.buildScript=function(a){var b=this.doc.createElement(a.tagName);d(a.attrs,function(a,c){b.setAttribute(a,c)});a.content&&(b.text=a.content);return b};e.prototype.insertScript=function(a){this.writeImpl('<span id="ps-script"/>');var b=this.doc.getElementById("ps-script");
b.parentNode.replaceChild(a,b)};e.prototype.scriptLoadHandler=function(a,b){function c(){e.onloadSetter(a,null);a.onreadystatechange=null;e.onerrorSetter(a,null)}function d(){c();b()}var e=this,f=this.options.error;e.onloadSetter(a,d);a.onreadystatechange=function(){var b=a.readyState;"loaded"!=b&&"complete"!=b||d()};e.onerrorSetter(a,function(){var d={message:"remote script failed "+a.src};c();f(d);b()})};e.prototype.shouldRelease=function(a){return!/^script$/i.test(a.nodeName)||!!(this.options.releaseAsync&&
a.src&&a.hasAttribute("async"))};return e}();k.postscribe=function(){function b(){var a=n.shift(),d;a&&(d=a[a.length-1],d.afterDequeue(),a.stream=c.apply(null,a),d.afterStreamStart())}function c(e,h,k){function n(a){a=k.beforeWrite(a);t.write(a);k.afterWrite(a)}t=Ic(new m(e,k),__mtm_tags&&__mtm_tags._writerConstructors,__mtm_tags&&__mtm_tags._writerModifiers,k);t.id=l++;t.name=k.name||t.id;d.streams[t.name]=t;var u=e.ownerDocument,x={close:u.close,open:u.open,write:u.write,writeln:u.writeln};f(u,
{close:a,open:a,write:function(){return n(g(arguments).join(""))},writeln:function(){return n(g(arguments).join("")+"\n")}});var w=t.win.onerror||a;t.win.onerror=function(a,b,c){if(!b&&(c=null,t)){var d=t.scriptStack[0];d&&(b=d.src)}k.error({msg:a+(b?" - "+b+(null===c?"":":"+c):" (inline script)"),errorMsg:a,url:b});w.apply(t.win,arguments)};t.write(h,function(){f(u,x);t.win.onerror=w;k.done();t=null;b()});return t}function d(c,f,g){"function"===typeof g&&(g={done:g});g=e(g,h);var k=[c,f,g];c.postscribe=
{cancel:function(){k.stream?k.stream.abort():k[1]=a}};g.beforeEnqueue(k);n.push(k);t||b();return c.postscribe}var l=0,n=[],t=null;return f(d,{streams:{},queue:n,WriteStream:m,HTMLParser:k.htmlParser})}()}).call(this);return this.postscribe}.call({}),Jc=function(a,b,c){__mtm_tags.curTag=c;try{n.write(b)}catch(d){__mtm_tags.curTag=0;c.error(d);return}__mtm_tags.curTag=0;c.done()},ba={postscribe:function(){return(ba.mode?Jc:Xa).apply(null,arguments)}};ba.postscribe.HTMLParser=Xa.HTMLParser;var Ic=function(a,
b,c){if(b)for(var d=0,f=b.length;d!=f;d++)b[d](a);if(!c)return a;var e=a.options,g,h,k=a.parser.append;a.parser.append=function(a){var b=a.length;h?h.substring(0,b)==a&&(g[1]+=b,h=h.substring(b)||null):g||(g=[0,b]);return k.apply(this,arguments)};var l=a.parser.prepend;a.parser.prepend=function(a){g&&g[1]&&(g[0]+=a.length);return l.apply(this,arguments)};var m=a.parser.clear;a.parser.clear=function(){g&&g[1]&&(h=this.rest(),g=[0,0]);return m.apply(this,arguments)};var p=function(b,d){for(var f=0,
g=c.length;f!=g;f++)c[f].call(a,b,d,e)},n=a.parser.readToken;a.parser.readToken=function(){var a;g&&g[1]&&(a=this.rest().length);var b=n.apply(this,arguments);if(!b||"startTag"!=b.type&&"atomicTag"!=b.type||"ps-script"==b.attrs.id)return b;var c=!1;g&&g[1]&&(a-=this.rest().length,g[0]>=a?g[0]-=a:(g[0]=0,p(b,!0),c=!0),0>(g[1]-=a)&&(g[1]=0));c||p(b,!1);return b};return a};m.__mtm_preview||(m.__mtm_preview=function(){__mtm_proc(__mtm_tags)});var Ka={};m.__mtm_proc||(m.__mtm_proc=function(a,b,c){if(b){if(Ka[b])Ka[b](a)}else if("object"==
typeof a&&null!==a&&a.tags){c||(a._asyncLoaded=1);if(a.previewMode!==w)if(a.previewExpire===w||1E3*a.previewExpire>(new y).getTime()){if(!a.previewMode){delete a.previewMode;delete a.previewExpire;m.__mtm_tags=a;__mtm_load("//tdi.mezzobit.com/tag-container/check-preview?c="+__mtm[0]);return}}else if(!a.enabled)return;m.__mtm_start||(b=la&&la.timing,m.__mtm_start=b?b.navigationStart||b.responseEnd:(new y).getTime());if(a.dg)__mtm_load("//"+__mtm[1]+"/mtm-"+a.dg+".js");else{var d=m.__mtm_tags;if(d){if(a._skipProfiler=
d._skipProfiler||d._standalone,a._profiler=d._profiler,a._getProfilerData=d._getProfilerData,a._writerModifiers=d._writerModifiers,a._overriddenAPIs=d._overriddenAPIs,a.postscribe=d.postscribe,a._api=d._api,d._tagStats&&(P=a._tagStats=d._tagStats),b=d._triggerEv){var f=n.documentElement;"function"==typeof b&&f.removeEventListener("sprofiler-msg",b);f.addEventListener("sprofiler-msg",a._triggerEv=function(a){z.apply(m,a.detail)})}}else a._api={};m.__mtm_tags=a;if(!a._overriddenAPIs){a._overriddenAPIs=
{innerHTMLSetter:function(a,b){a.innerHTML=b},onloadSetter:function(a,b){a.onload=b},onerrorSetter:function(a,b){a.onerror=b}};var e=["setTimeout","setInterval"];for(b=0;2!=b;b++)(function(b){b=e[b];var c=m[b];a._overriddenAPIs[b]=c.apply?function(){return c.apply(m,arguments)}:function(a,b){return c(a,b)}})(b)}ba.mode=c;a.postscribe||(a.postscribe=ba.postscribe);c=a.debug||a.vs||a.crules;if(a._skipProfiler)a.debug||(m.__mtm_data_sent=1),c||m.__mtm_spy--;else{if(!a._profiler&&c&&db()){__mtm_load(xa("profile"));
return}c&&!a._getProfilerData&&(a._profiler&&db()?a._getProfilerData=a._profiler(P,a.extdbg?function(){return 1}:0,0,z,a._overriddenAPIs,1):a._getProfilerData=Nb)}a.timezones&&a.timezones[a.timezone]&&(qa[a.timezone]=mb(pa,a.timezones[a.timezone]),delete a.timezones[a.timezone]);if(Na(a.activityPeriodRules,qa[a.timezone]||pa)){if(a.timezones)for(var g in a.timezones)qa[g]=mb(pa,a.timezones[g]);if(a._controlLoaded)ia=a._controlRules;else if(a._controlLoaded=1,ia=a._controlRules=sc(),(a._profiler||
d&&d._standalone)&&a.crules){g=function(a,b){return function(c){Cb(a,function(a){a&&ia.push(b,a);c()})}};Wb([g(a.controlRules,"g"),g(a.extControlRules,"o")],function(){__mtm_load(xa("control"))});return}if(a.vs){if(!a._tageventsLoaded){a._tageventsLoaded=1;__mtm_load(xa("tagevents"));return}a._tagEventsInit||(a._tagEventsInit=1,a._tagevents(fa,ra,z,T,U,Ra,rb,ca,Fa,yc,ab,F,P,a.vs.prof))}a.rules||(a.rules={});ec();var h="yes"==S.doNotTrack||"yes"==S.msDoNotTrack;fc();Hc(a);var k=[],l=function(b){var c=
b.depends,d;if(c&&(d=c.length))for(var e=0;e!=d;e++){var f="-"+c[e];I[f]||(I[f]={});I[f][b.id]=1}Kb(b,function(e,f,g){e={code:e,place:f,state:g};if(d)for(da[b.id]=[e,d],e=0;e!=d;e++)f="-"+c[e],ea[f]&&ya(f);else e=[e,b.id],b.activationDelay?a._overriddenAPIs.setTimeout(fa([e]),b.activationDelay):r?k.push(e):fa([e])()})};g=a.tags;c=function(b){var c=b.timezone||a.timezone;if(!(h&&!b.place||!Na(b.activityPeriodRules,qa[c]||pa)||b.pathname&&X.pathname!=b.pathname&&X.pathname!=b.pathname+"/")){if(b.query){ub();
for(var d in b.query)if(b.query[d]!=sa[d])return}var e;Mb(b,function(){e?l(b):(e=1,Cb(b.controlRules,function(a){a&&ia.push(b.id,a);l(b)}))})}};var r=1,d=g.length;for(b=0;b!=d;b++)f=g[b],F.add(f.id,f);for(b=0;b<g.length;b++)c(g[b]);r=0;k.length&&fa(k)();a.debug&&a._profLogger&&a._profLogger(a._getProfilerData)}}}});var W=m.__mtm_tags;W&&W._asyncLoaded||(!W||W._standalone||W._syncLoaded?(W&&(W._asyncLoaded=1),__mtm_load("//"+__mtm[1]+"/"+__mtm[0]+".js")):__mtm_proc(W))}})(window,document,navigator,
location,Object,Array,Date,RegExp);
