languageCode: "en-us"
title: "Art / Earth / Tech"
baseURL: "/"
googleAnalytics: "UA-102022428-1"

permalinks:
  blog: /:year/:month/:day/:slug/

params:
  github: https://github.com/artearthtech
  twitter: https://twitter.com/ArtEarthTech
  facebook: https://www.facebook.com/ArtEarthTech/
  instagram: https://www.instagram.com/artearthtech/
