---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: content/gathering
  label: Gathering
  create: all
  match: "**/*"
- type: directory
  path: content/hubs
  label: Hubs
  create: all
  match: "**/*"
- type: directory
  path: content/initiatives
  label: Initiatives
  create: all
  match: "**/*"
- type: directory
  path: content/institute
  label: Institute
  create: all
  match: "**/*"
- type: directory
  path: content/news
  label: News
  create: all
  match: "**/*"
- type: directory
  path: content/people
  label: People
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
